export const countries = {
  مصر: {
    nameEn: "Egypt",
    ar: [
      "القاهرة",
      "الجيزة",
      "الإسكندرية",
      "السويس",
      "بورسعيد",
      "دمياط",
      "الدقهلية",
      "كفر الشيخ",
      "الشرقية",
      "الغربية",
      "المنوفية",
      "المنيا",
      "بني سويف",
      "أسيوط",
      "سوهاج",
      "قنا",
      "الأقصر",
      "أسوان",
      "البحر الأحمر",
      "الوادي الجديد",
      "مطروح",
      "شمال سيناء",
      "جنوب سيناء",
      "الإسماعيلية",
    ],
    en: [
      "Cairo",
      "Giza",
      "Alexandria",
      "Suez",
      "Port Said",
      "Damietta",
      "Dakahlia",
      "Kafr El-Sheikh",
      "Sharqia",
      "Gharbia",
      "Monufia",
      "Minya",
      "Beni Suef",
      "Assiut",
      "Sohag",
      "Qena",
      "Luxor",
      "Aswan",
      "Red Sea",
      "New Valley",
      "Matrouh",
      "North Sinai",
      "South Sinai",
      "Ismailia",
    ],
  },
  السعودية: {
    nameEn: "Saudi Arabia",
    ar: [
      "الرياض",
      "جدة",
      "مكة المكرمة",
      "المدينة المنورة",
      "الدمام",
      "الخبر",
      "الطائف",
      "القصيم",
      "حائل",
      "نجران",
      "أبها",
      "جازان",
    ],
    en: [
      "Riyadh",
      "Jeddah",
      "Mecca",
      "Medina",
      "Dammam",
      "Khobar",
      "Taif",
      "Qassim",
      "Hail",
      "Najran",
      "Abha",
      "Jazan",
    ],
  },
  الإمارات: {
    nameEn: "United Arab Emirates",
    ar: [
      "أبوظبي",
      "دبي",
      "الشارقة",
      "عجمان",
      "الفجيرة",
      "راس الخيمة",
      "أم القيوين",
    ],
    en: [
      "Abu Dhabi",
      "Dubai",
      "Sharjah",
      "Ajman",
      "Fujairah",
      "Ras Al Khaimah",
      "Umm Al Quwain",
    ],
  },
  البحرين: {
    nameEn: "Bahrain",
    ar: ["المنامة", "المحرق", "الحد"],
    en: ["Manama", "Muharraq", "Al-Hidd"],
  },
  الكويت: {
    nameEn: "Kuwait",
    ar: ["الكويت", "الفروانية", "حولي", "الأحمدي", "الجهراء"],
    en: ["Kuwait City", "Farwaniya", "Hawally", "Ahmadi", "Jahra"],
  },
  عمان: {
    nameEn: "Oman",
    ar: ["مسقط", "صلالة", "نزوى"],
    en: ["Muscat", "Salalah", "Nizwa"],
  },
  قطر: {
    nameEn: "Qatar",
    ar: ["الدوحة", "الخور", "الوكرة"],
    en: ["Doha", "Al Khor", "Al Wakrah"],
  },
  العراق: {
    nameEn: "Iraq",
    ar: ["بغداد", "البصرة", "الموصل", "النجف", "كربلاء", "السليمانية"],
    en: ["Baghdad", "Basra", "Mosul", "Najaf", "Karbala", "Sulaymaniyah"],
  },
  الأردن: {
    nameEn: "Jordan",
    ar: ["عمان", "إربد", "الزرقاء", "مأدبا", "جرش", "عجلون"],
    en: ["Amman", "Irbid", "Zarqa", "Madaba", "Jerash", "Ajloun"],
  },
  الجزائر: {
    nameEn: "Algeria",
    ar: ["الجزائر", "وهران", "قسنطينة", "تلمسان", "عنابة"],
    en: ["Algiers", "Oran", "Constantine", "Tlemcen", "Annaba"],
  },
  المغرب: {
    nameEn: "Morocco",
    ar: ["الرباط", "الدار البيضاء", "مراكش", "فاس", "أكادير"],
    en: ["Rabat", "Casablanca", "Marrakech", "Fes", "Agadir"],
  },
  تونس: {
    nameEn: "Tunisia",
    ar: ["تونس", "سوسة", "صفاقس", "نابل", "المهدية"],
    en: ["Tunis", "Sousse", "Sfax", "Nabeul", "Mahdia"],
  },
  ليبيا: {
    nameEn: "Libya",
    ar: ["طرابلس", "بنغازي", "مصراتة", "سبها", "البيضاء"],
    en: ["Tripoli", "Benghazi", "Misrata", "Sebha", "Al Bayda"],
  },
  تركيا: {
    nameEn: "Turkey",
    ar: ["إسطنبول", "أنقرة", "أزمير", "بورصة", "أنطاليا"],
    en: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  },
  ماليزيا: {
    nameEn: "Malaysia",
    ar: ["كوالالمبور", "بترا جاي", "بينانج", "سارواك", "صباح"],
    en: ["Kuala Lumpur", "Putrajaya", "Penang", "Sarawak", "Sabah"],
  },
  إندونيسيا: {
    nameEn: "Indonesia",
    ar: ["جاكرتا", "بالي", "سورابايا", "باندونغ", "ميدان"],
    en: ["Jakarta", "Bali", "Surabaya", "Bandung", "Medan"],
  },

  باكستان: {
    nameEn: "Pakistan",
    ar: ["إسلام آباد", "كراشي", "لاهور", "راولبندي", "حيدر آباد"],
    en: ["Islamabad", "Karachi", "Lahore", "Rawalpindi", "Hyderabad"],
  },
  أفغانستان: {
    nameEn: "Afghanistan",
    ar: ["كابول", "هيرات", "مزار شريف", "جلال آباد", "قندهار"],
    en: ["Kabul", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kandahar"],
  },
  السودان: {
    nameEn: "Sudan",
    ar: ["الخرطوم", "أم درمان", "مدني", "بورتسودان", "نيالا"],
    en: ["Khartoum", "Omdurman", "Medani", "Port Sudan", "Nyala"],
  },
  سوريا: {
    nameEn: "Syria",
    ar: ["دمشق", "حلب", "حمص", "اللاذقية", "درعا"],
    en: ["Damascus", "Aleppo", "Homs", "Latakia", "Daraa"],
  },
  فلسطين: {
    nameEn: "Palestine",
    ar: ["القدس", "غزة", "رام الله", "بيت لحم", "الخليل"],
    en: ["Jerusalem", "Gaza", "Ramallah", "Bethlehem", "Hebron"],
  },
  جزر_القمر: {
    nameEn: "Comoros",
    ar: ["موروني"],
    en: ["Moroni"],
  },
  المالديف: {
    nameEn: "Maldives",
    ar: ["ماليه"],
    en: ["Male"],
  },
  سنغافورة: {
    nameEn: "Singapore",
    ar: ["سنغافورة"],
    en: ["Singapore"],
  },
};
