export const availableLanguages = [
  { id: "ar" },
  { id: "eng" },
  { id: "fr" },
  { id: "ru" },
  { id: "de" },
  { id: "es" },
  { id: "tr" },
  { id: "cn" },
  { id: "th" },
  { id: "ur" },
  { id: "bn" },
  { id: "bs" },
  { id: "ug" },
  { id: "fa" },
  { id: "tg" },
  { id: "ml" },
  { id: "tl" },
  { id: "id" },
  { id: "pt" },
  { id: "ha" },
  { id: "sw" },
];

export const MultiLanguage = [
  {
    ar: {
      id: "ar",
      lang: "العربية",
      headerTitle: "القراَن الكريم",
      navbar: [
        {
          home: "الرئيسية",
          quran: "القرآن",
          reader: "القراء",
          radio: "الراديو",
          live: "بث مباشر",
          prayer: "الصلاة",
          sebha: "السبحة",
          settings: "الأعدادات",
        },
      ],
      themes: [{ light: "فاتح", simpledark: "داكن", dark: "غامق" }],
      icons: [{ styleOne: "نمط الأيقونات  ۱", styleTwo: "نمط الأيقونات  ۲" }],
      fonts: [
        {
          hafs: "حفص",
          qaloun: "قالون",
          nastaleeq: "نستعليق",
          amiri: "العامري",
        },
      ],
      home: [
        {
          currentBookmarks: "العلامات المرجعية الموضوعة",
          SurahFavorites: "السور المفضلة",
        },
      ],
      quran: [
        {
          quranTitle: "القرآن الكريم",
          searchPlaceHolder: "ابحث باسم السورة",
          ayat: "آيات",
          numberOfAyahs: "عدد الآيات",
          surahOrder: "ترتيب السورة",
          revelation: "النزول",
          revelationType1: "مكية",
          revelationType2: "مدنية",
          reading: "القراءة",
          interpretation: "التفسير",
          translation: "الترجمة",
          listening: "الأستماع",
          alsurah: "السورة",
          aljuz: "الجزء",
          alhizb: "الحزب",
          alsafha: "الصفحة",
          ayah: "آية",
          ayahPlay: "تشغيل الآية",
          ayahTafsier: "تفسير الآية",
          ayahBookmark: "علامة مرجعية",
          tafsierPlaceholder: "اختر التفسير",
          translationPlaceholder: "اختر الترجمة",
          translationButton: "عرض الترجمة",
          translationNotes: "اختر الترجمة واضغط للعرض",
        },
      ],
      readers: [
        {
          quranTitle: "القرآن الكريم",
          searchPlaceHolder: "ابحث باسم القارئ",
          searchPlaceHolder2: "ابحث باسم السورة",
          copyBtn: "نسخ رابط السورة",
          downloadBtn: "تحميل السورة",
          playBtn: "تشغيل السورة",
        },
      ],
      radio: [{ quranTitle: "راديو القرآن الكريم" }],
      tv: [{ quranTitle: "مباشر القرآن الكريم" }],
      prayerTime: [
        {
          quranTitle: "أوقات الصلاة",
          gregorianDate: "التاريخ الميلادي",
          hijriDate: "التاريخ الهجري",
          month: "الشهر",
          am: "ص",
          pm: "م",
          methods: ["طريقة 1", "طريقة 2", "طريقة 3", "طريقة 4", "طريقة 5"],
          Fajr: "الفجر",
          Sunrise: "الشروق",
          Dhuhr: "الظهر",
          Asr: "العصر",
          Maghrib: "المغرب",
          Isha: "العشاء",
        },
      ],
      tasbeh: [
        {
          quranTitle: "تسبيح",
          buttonTasbehStart: "تفعيل التسبيح بعد الصلاة",
          buttonTasbehStop: "إنهاء التسبيح بعد الصلاة",
          tasbihLetters: ["سبحان الله", "الحمد لله", "الله أكبر"],
        },
      ],
    },
    eng: {
      id: "eng",
      lang: "English",
      headerTitle: "Quran",
      navbar: [
        {
          home: "Home",
          quran: "Quran",
          reader: "Readers",
          radio: "Radio",
          live: "Live",
          prayer: "Prayer",
          sebha: "Tasbih",
          settings: "Settings",
        },
      ],
      themes: [{ light: "Light", simpledark: "Dark", dark: "Dark" }],
      icons: [{ styleOne: "Icon Style 1", styleTwo: "Icon Style 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Current Bookmarks",
          SurahFavorites: "Surah Favorites",
        },
      ],
      quran: [
        {
          quranTitle: "The Holy Quran",
          searchPlaceHolder: "Search by Surah name",
          ayat: "Ayahs",
          numberOfAyahs: "Number of Ayahs",
          surahOrder: "Surah Order",
          revelation: "Revelation",
          revelationType1: "Meccan",
          revelationType2: "Medinan",
          reading: "Reading",
          interpretation: "Interpretation",
          translation: "Translation",
          listening: "Listening",
          alsurah: "Surah",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Page",
          ayah: "Ayah",
          ayahPlay: "Play Ayah",
          ayahTafsier: "Ayah Interpretation",
          ayahBookmark: "Bookmark",
          tafsierPlaceholder: "Select Interpretation",
          translationPlaceholder: "Select Translation",
          translationButton: "Show Translation",
          translationNotes: "Select translation and click to view",
        },
      ],
      readers: [
        {
          quranTitle: "Quran",
          searchPlaceHolder: "Search by Reader's name",
          searchPlaceHolder2: "Search by Surah name",
          copyBtn: "Copy Surah Link",
          downloadBtn: "Download Surah",
          playBtn: "Play Surah",
        },
      ],
      radio: [{ quranTitle: "Quran Radio" }],
      tv: [{ quranTitle: "Quran Live" }],
      prayerTime: [
        {
          quranTitle: "Prayer Times",
          gregorianDate: "Gregorian Date",
          hijriDate: "Hijri Date",
          month: "Month",
          am: "AM",
          pm: "PM",
          methods: ["Method 1", "Method 2", "Method 3", "Method 4", "Method 5"],
          Fajr: "Fajr",
          Sunrise: "Sunrise",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbeeh",
          buttonTasbehStart: "Start Tasbeeh after Prayer",
          buttonTasbehStop: "Stop Tasbeeh after Prayer",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },

    fr: {
      id: "fr",
      lang: "Français",
      headerTitle: "Coran",
      navbar: [
        {
          home: "Accueil",
          quran: "Coran",
          reader: "Lecteurs",
          radio: "Radio",
          live: "En direct",
          prayer: "Prière",
          sebha: "Chapelet",
          settings: "Paramètres",
        },
      ],
      themes: [{ light: "Clair", simpledark: "Foncé", dark: "Sombre" }],
      icons: [{ styleOne: "Style d'icônes 1", styleTwo: "Style d'icônes 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Signets actuels",
          SurahFavorites: "Sourates Préférées",
        },
      ],
      quran: [
        {
          quranTitle: "Le Noble Coran",
          searchPlaceHolder: "Rechercher par nom de Sourate",
          ayat: "Versets",
          numberOfAyahs: "Nombre de versets",
          surahOrder: "Ordre de la Sourate",
          revelation: "Révélation",
          revelationType1: "Mecquoise",
          revelationType2: "Médinoise",
          reading: "Lecture",
          interpretation: "Interprétation",
          translation: "Traduction",
          listening: "Écoute",
          alsurah: "Sourate",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Page",
          ayah: "Verset",
          ayahPlay: "Lire le verset",
          ayahTafsier: "Interprétation du verset",
          ayahBookmark: "Signet",
          tafsierPlaceholder: "Sélectionner l'interprétation",
          translationPlaceholder: "Sélectionner la traduction",
          translationButton: "Afficher la traduction",
          translationNotes: "Sélectionnez la traduction et cliquez pour voir",
        },
      ],
      readers: [
        {
          quranTitle: "Coran",
          searchPlaceHolder: "Rechercher par nom du lecteur",
          searchPlaceHolder2: "Rechercher par nom de Sourate",
          copyBtn: "Copier le lien de la sourate",
          downloadBtn: "Télécharger la sourate",
          playBtn: "Jouer la sourate",
        },
      ],
      radio: [{ quranTitle: "Radio du Coran" }],
      tv: [{ quranTitle: "Coran en direct" }],
      prayerTime: [
        {
          quranTitle: "Heures de prière",
          gregorianDate: "Date grégorienne",
          hijriDate: "Date hégirienne",
          month: "Mois",
          am: "AM",
          pm: "PM",
          methods: [
            "Méthode 1",
            "Méthode 2",
            "Méthode 3",
            "Méthode 4",
            "Méthode 5",
          ],
          Fajr: "Fajr",
          Sunrise: "Lever du soleil",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbeeh",
          buttonTasbehStart: "Commencer le Tasbeeh après la prière",
          buttonTasbehStop: "Arrêter le Tasbeeh après la prière",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },

    ru: {
      id: "ru",
      lang: "Русский",
      headerTitle: "Коран",
      navbar: [
        {
          home: "Главная",
          quran: "Коран",
          reader: "Чтецы",
          radio: "Радио",
          live: "В прямом эфире",
          prayer: "Молитва",
          sebha: "Тасбих",
          settings: "Настройки",
        },
      ],
      themes: [{ light: "Светлый", simpledark: "Темный", dark: "Темный" }],
      icons: [{ styleOne: "Стиль иконки 1", styleTwo: "Стиль иконки 2" }],
      fonts: [
        {
          hafs: "Хафс",
          qaloun: "Калун",
          nastaleeq: "Насталик",
          amiri: "Амири",
        },
      ],
      home: [
        {
          currentBookmarks: "Текущие закладки",
          SurahFavorites: "Любимые суры",
        },
      ],
      quran: [
        {
          quranTitle: "Священный Коран",
          searchPlaceHolder: "Искать по имени суры",
          ayat: "Аяты",
          numberOfAyahs: "Количество аятов",
          surahOrder: "Порядок суры",
          revelation: "Откровение",
          revelationType1: "Мекканская",
          revelationType2: "Мединская",
          reading: "Чтение",
          interpretation: "Толкование",
          translation: "Перевод",
          listening: "Прослушивание",
          alsurah: "Сура",
          aljuz: "Джуз",
          alhizb: "Хизб",
          alsafha: "Страница",
          ayah: "Аят",
          ayahPlay: "Воспроизвести аят",
          ayahTafsier: "Толкование аята",
          ayahBookmark: "Закладка",
          tafsierPlaceholder: "Выберите толкование",
          translationPlaceholder: "Выберите перевод",
          translationButton: "Показать перевод",
          translationNotes: "Выберите перевод и нажмите, чтобы просмотреть",
        },
      ],
      readers: [
        {
          quranTitle: "Коран",
          searchPlaceHolder: "Поиск по имени чтеца",
          searchPlaceHolder2: "Поиск по названию суры",
          copyBtn: "Скопировать ссылку на суре",
          downloadBtn: "Скачать суре",
          playBtn: "Воспроизвести суре",
        },
      ],
      radio: [{ quranTitle: "Радио Корана" }],
      tv: [{ quranTitle: "Прямой эфир Корана" }],
      prayerTime: [
        {
          quranTitle: "Время молитвы",
          gregorianDate: "Григорианская дата",
          hijriDate: "Хиджри дата",
          month: "Месяц",
          am: "AM",
          pm: "PM",
          methods: ["Метод 1", "Метод 2", "Метод 3", "Метод 4", "Метод 5"],
          Fajr: "Фаджр",
          Sunrise: "Восход солнца",
          Dhuhr: "Зухр",
          Asr: "Аср",
          Maghrib: "Магриб",
          Isha: "Иша",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Тасбих",
          buttonTasbehStart: "Начать тасбих после молитвы",
          buttonTasbehStop: "Остановить тасбих после молитвы",
          tasbihLetters: ["СубханАллах", "Альхамдулиллах", "Аллаху Акбар"],
        },
      ],
    },

    de: {
      id: "de",
      lang: "Deutsch",
      headerTitle: "Koran",
      navbar: [
        {
          home: "Startseite",
          quran: "Koran",
          reader: "Leser",
          radio: "Radio",
          live: "Live",
          prayer: "Gebet",
          sebha: "Tasbih",
          settings: "Einstellungen",
        },
      ],
      themes: [{ light: "Hell", simpledark: "Dunkel", dark: "Dunkel" }],
      icons: [{ styleOne: "Symbolstil 1", styleTwo: "Symbolstil 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Aktuelle Lesezeichen",
          SurahFavorites: "Bevorzugte Suren",
        },
      ],
      quran: [
        {
          quranTitle: "Der Heilige Koran",
          searchPlaceHolder: "Nach Surenname suchen",
          ayat: "Verse",
          numberOfAyahs: "Anzahl der Verse",
          surahOrder: "Reihenfolge der Suren",
          revelation: "Offenbarung",
          revelationType1: "Mekkanisch",
          revelationType2: "Medinensisch",
          reading: "Lesen",
          interpretation: "Interpretation",
          translation: "Übersetzung",
          listening: "Hören",
          alsurah: "Sure",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Seite",
          ayah: "Vers",
          ayahPlay: "Vers abspielen",
          ayahTafsier: "Versinterpretation",
          ayahBookmark: "Lesezeichen",
          tafsierPlaceholder: "Interpretation auswählen",
          translationPlaceholder: "Übersetzung auswählen",
          translationButton: "Übersetzung anzeigen",
          translationNotes: "Übersetzung auswählen und klicken, um anzuzeigen",
        },
      ],
      readers: [
        {
          quranTitle: "Koran",
          searchPlaceHolder: "Nach Namen des Lesers suchen",
          searchPlaceHolder2: "Nach Surenname suchen",
          copyBtn: "Kopiere Surah-Link",
          downloadBtn: "Surah herunterladen",
          playBtn: "Surah abspielen",
        },
      ],
      radio: [{ quranTitle: "Koran-Radio" }],
      tv: [{ quranTitle: "Live Koran" }],
      prayerTime: [
        {
          quranTitle: "Gebetszeiten",
          gregorianDate: "Gregorianisches Datum",
          hijriDate: "Hidschri-Datum",
          month: "Monat",
          am: "AM",
          pm: "PM",
          methods: [
            "Methode 1",
            "Methode 2",
            "Methode 3",
            "Methode 4",
            "Methode 5",
          ],
          Fajr: "Fajr",
          Sunrise: "Sonnenaufgang",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbeeh",
          buttonTasbehStart: "Tasbeeh nach dem Gebet starten",
          buttonTasbehStop: "Tasbeeh nach dem Gebet beenden",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },

    es: {
      id: "es",
      lang: "Español",
      headerTitle: "Corán",
      navbar: [
        {
          home: "Inicio",
          quran: "Corán",
          reader: "Lectores",
          radio: "Radio",
          live: "En vivo",
          prayer: "Oración",
          sebha: "Tasbih",
          settings: "Ajustes",
        },
      ],
      themes: [{ light: "Claro", simpledark: "Oscuro", dark: "Oscuro" }],
      icons: [
        { styleOne: "Estilo de íconos 1", styleTwo: "Estilo de íconos 2" },
      ],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Marcadores actuales",
          SurahFavorites: "Suras Favoritas",
        },
      ],
      quran: [
        {
          quranTitle: "El Sagrado Corán",
          searchPlaceHolder: "Buscar por nombre de sura",
          ayat: "Aleyas",
          numberOfAyahs: "Número de aleyas",
          surahOrder: "Orden de la sura",
          revelation: "Revelación",
          revelationType1: "Meca",
          revelationType2: "Medina",
          reading: "Lectura",
          interpretation: "Interpretación",
          translation: "Traducción",
          listening: "Escuchar",
          alsurah: "Sura",
          aljuz: "Yuz",
          alhizb: "Hizb",
          alsafha: "Página",
          ayah: "Aleya",
          ayahPlay: "Reproducir aleya",
          ayahTafsier: "Interpretación de la aleya",
          ayahBookmark: "Marcador",
          tafsierPlaceholder: "Seleccionar interpretación",
          translationPlaceholder: "Seleccionar traducción",
          translationButton: "Mostrar traducción",
          translationNotes: "Seleccione la traducción y haga clic para ver",
        },
      ],
      readers: [
        {
          quranTitle: "Corán",
          searchPlaceHolder: "Buscar por nombre del lector",
          searchPlaceHolder2: "Buscar por nombre de Surah",
          copyBtn: "Copiar enlace de la sura",
          downloadBtn: "Descargar sura",
          playBtn: "Reproducir sura",
        },
      ],
      radio: [{ quranTitle: "Radio del Corán" }],
      tv: [{ quranTitle: "Corán en Vivo" }],
      prayerTime: [
        {
          quranTitle: "Horas de oración",
          gregorianDate: "Fecha gregoriana",
          hijriDate: "Fecha hégira",
          month: "Mes",
          am: "AM",
          pm: "PM",
          methods: ["Método 1", "Método 2", "Método 3", "Método 4", "Método 5"],
          Fajr: "Fajr",
          Sunrise: "Amanecer",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbih",
          buttonTasbehStart: "Iniciar Tasbih después de la oración",
          buttonTasbehStop: "Detener Tasbih después de la oración",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },

    tr: {
      id: "tr",
      lang: "Türkçe",
      headerTitle: "Kuran",
      navbar: [
        {
          home: "Ana Sayfa",
          quran: "Kuran",
          reader: "Okuyucular",
          radio: "Radyo",
          live: "Canlı",
          prayer: "Namaz",
          sebha: "Tesbih",
          settings: "Ayarlar",
        },
      ],
      themes: [{ light: "Açık", simpledark: "Koyu", dark: "Koyu" }],
      icons: [{ styleOne: "Simge Stili 1", styleTwo: "Simge Stili 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Kalun",
          nastaleeq: "Nastalik",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Mevcut Yer İmleri",
          SurahFavorites: "Favori Sureler",
        },
      ],
      quran: [
        {
          quranTitle: "Kur'an-ı Kerim",
          searchPlaceHolder: "Sure ismi ile ara",
          ayat: "Ayetler",
          numberOfAyahs: "Ayet Sayısı",
          surahOrder: "Sure Sırası",
          revelation: "Vahiy",
          revelationType1: "Mekki",
          revelationType2: "Medeni",
          reading: "Okuma",
          interpretation: "Tefsir",
          translation: "Tercüme",
          listening: "Dinleme",
          alsurah: "Sure",
          aljuz: "Cüz",
          alhizb: "Hizb",
          alsafha: "Sayfa",
          ayah: "Ayet",
          ayahPlay: "Ayet Oynat",
          ayahTafsier: "Ayet Tefsiri",
          ayahBookmark: "Yer İmi",
          tafsierPlaceholder: "Tefsir Seçin",
          translationPlaceholder: "Çeviri Seçin",
          translationButton: "Çeviriyi Göster",
          translationNotes: "Çeviriyi seçin ve görmek için tıklayın",
        },
      ],
      readers: [
        {
          quranTitle: "Kuran",
          searchPlaceHolder: "Okuyucu adıyla ara",
          searchPlaceHolder2: "Sure ismiyle ara",
          copyBtn: "Sure Linkini Kopyala",
          downloadBtn: "Sureyi İndir",
          playBtn: "Sureyi Çal",
        },
      ],
      radio: [{ quranTitle: "Kuran Radyosu" }],
      tv: [{ quranTitle: "Canlı Kuran" }],
      prayerTime: [
        {
          quranTitle: "Namaz Vakitleri",
          gregorianDate: "Miladi Tarih",
          hijriDate: "Hicri Tarih",
          month: "Ay",
          am: "ÖÖ",
          pm: "ÖS",
          methods: ["Yöntem 1", "Yöntem 2", "Yöntem 3", "Yöntem 4", "Yöntem 5"],
          Fajr: "Sabah",
          Sunrise: "Güneş",
          Dhuhr: "Öğle",
          Asr: "İkindi",
          Maghrib: "Akşam",
          Isha: "Yatsı",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tesbih",
          buttonTasbehStart: "Namazdan Sonra Tesbihi Başlat",
          buttonTasbehStop: "Namazdan Sonra Tesbihi Durdur",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },

    cn: {
      id: "cn",
      lang: "中文",
      headerTitle: "古兰经",
      navbar: [
        {
          home: "主页",
          quran: "古兰经",
          reader: "读者",
          radio: "广播",
          live: "直播",
          prayer: "祷告",
          sebha: "祷珠",
          settings: "设置",
        },
      ],
      themes: [{ light: "浅色", simpledark: "黑暗", dark: "深色" }],
      icons: [{ styleOne: "图标样式 1", styleTwo: "图标样式 2" }],
      fonts: [
        {
          hafs: "哈弗斯",
          qaloun: "卡卢恩",
          nastaleeq: "纳斯塔里克",
          amiri: "阿米里",
        },
      ],
      home: [{ currentBookmarks: "当前书签", SurahFavorites: "喜爱的苏拉" }],
      quran: [
        {
          quranTitle: "古兰经",
          searchPlaceHolder: "按苏拉名称搜索",
          ayat: "节",
          numberOfAyahs: "节数",
          surahOrder: "苏拉顺序",
          revelation: "启示",
          revelationType1: "麦加",
          revelationType2: "麦地那",
          reading: "阅读",
          interpretation: "释义",
          translation: "翻译",
          listening: "收听",
          alsurah: "苏拉",
          aljuz: "卷",
          alhizb: "组",
          alsafha: "页",
          ayah: "节文",
          ayahPlay: "播放节文",
          ayahTafsier: "节文释义",
          ayahBookmark: "书签",
          tafsierPlaceholder: "选择释义",
          translationPlaceholder: "选择翻译",
          translationButton: "显示翻译",
          translationNotes: "选择翻译并点击查看",
        },
      ],
      readers: [
        {
          quranTitle: "古兰经",
          searchPlaceHolder: "按读者姓名搜索",
          searchPlaceHolder2: "按苏拉名称搜索",
          copyBtn: "复制苏拉链接",
          downloadBtn: "下载苏拉",
          playBtn: "播放苏拉",
        },
      ],
      radio: [{ quranTitle: "古兰经广播" }],
      tv: [{ quranTitle: "古兰经直播" }],
      prayerTime: [
        {
          quranTitle: "祈祷时间",
          gregorianDate: "公历日期",
          hijriDate: "伊斯兰历日期",
          month: "月",
          am: "上午",
          pm: "下午",
          methods: ["方法 1", "方法 2", "方法 3", "方法 4", "方法 5"],
          Fajr: "晨礼",
          Sunrise: "日出",
          Dhuhr: "晌礼",
          Asr: "晡礼",
          Maghrib: "昏礼",
          Isha: "宵礼",
        },
      ],
      tasbeh: [
        {
          quranTitle: "赞颂",
          buttonTasbehStart: "祷告后开始赞颂",
          buttonTasbehStop: "祷告后停止赞颂",
          tasbihLetters: ["赞美真主", "一切赞美归于真主", "真主至大"],
        },
      ],
    },

    th: {
      id: "th",
      lang: "ไทย",
      headerTitle: "อัลกุรอาน",
      navbar: [
        {
          home: "หน้าแรก",
          quran: "คัมภีร์อัลกุรอาน",
          reader: "ผู้อ่าน",
          radio: "วิทยุ",
          live: "ถ่ายทอดสด",
          prayer: "การสวดมนต์",
          sebha: "ลูกประคำ",
          settings: "การตั้งค่า",
        },
      ],
      themes: [{ light: "แสงสว่าง", simpledark: "มืด", dark: "มืด" }],
      icons: [{ styleOne: "สไตล์ไอคอน 1", styleTwo: "สไตล์ไอคอน 2" }],
      fonts: [
        {
          hafs: "ฮัฟส์",
          qaloun: "คาลูน",
          nastaleeq: "นาสตาลีค",
          amiri: "อะมีรี",
        },
      ],
      home: [
        {
          currentBookmarks: "บุ๊กมาร์กปัจจุบัน",
          SurahFavorites: "ซูเราะห์ที่ชื่นชอบ",
        },
      ],
      quran: [
        {
          quranTitle: "อัลกุรอาน",
          searchPlaceHolder: "ค้นหาด้วยชื่อซูเราะห์",
          ayat: "อายะห์",
          numberOfAyahs: "จำนวนอายะห์",
          surahOrder: "ลำดับซูเราะห์",
          revelation: "การเปิดเผย",
          revelationType1: "เมกกะห์",
          revelationType2: "มะดีนะห์",
          reading: "การอ่าน",
          interpretation: "การตีความ",
          translation: "การแปล",
          listening: "การฟัง",
          alsurah: "ซูเราะห์",
          aljuz: "ญุซ",
          alhizb: "ฮิซบ์",
          alsafha: "หน้า",
          ayah: "อายะห์",
          ayahPlay: "เล่นอายะห์",
          ayahTafsier: "ตีความอายะห์",
          ayahBookmark: "บุ๊คมาร์ก",
          tafsierPlaceholder: "เลือกการตีความ",
          translationPlaceholder: "เลือกการแปล",
          translationButton: "แสดงการแปล",
          translationNotes: "เลือกการแปลแล้วคลิกเพื่อดู",
        },
      ],
      readers: [
        {
          quranTitle: "อัลกุรอาน",
          searchPlaceHolder: "ค้นหาตามชื่อผู้อ่าน",
          searchPlaceHolder2: "ค้นหาตามชื่อซูเราะห์",
          copyBtn: "คัดลอกลิงก์ซูระ",
          downloadBtn: "ดาวน์โหลดซูระ",
          playBtn: "เล่นซูระ",
        },
      ],
      radio: [{ quranTitle: "วิทยุกุรอาน" }],
      tv: [{ quranTitle: "ถ่ายทอดสดอัลกุรอาน" }],
      prayerTime: [
        {
          quranTitle: "เวลาละหมาด",
          gregorianDate: "วันที่ตามปฏิทินเกรกอเรียน",
          hijriDate: "วันที่ตามปฏิทินฮิจเราะห์",
          month: "เดือน",
          am: "เช้า",
          pm: "บ่าย",
          methods: [
            "วิธีที่ 1",
            "วิธีที่ 2",
            "วิธีที่ 3",
            "วิธีที่ 4",
            "วิธีที่ 5",
          ],
          Fajr: "ฟัจญ์ร",
          Sunrise: "พระอาทิตย์ขึ้น",
          Dhuhr: "ดุฮริ",
          Asr: "อัสริ",
          Maghrib: "มัฆริบ",
          Isha: "อิชาอ์",
        },
      ],
      tasbeh: [
        {
          quranTitle: "การสรรเสริญ",
          buttonTasbehStart: "เริ่มสรรเสริญหลังการละหมาด",
          buttonTasbehStop: "หยุดสรรเสริญหลังการละหมาด",
          tasbihLetters: ["ซุบฮานัลลอฮ์", "อัลฮัมดุลิลละฮ์", "อัลลอฮ์อักบัร"],
        },
      ],
    },

    ur: {
      id: "ur",
      lang: "اردو",
      headerTitle: "قرآن",
      navbar: [
        {
          home: "صفحہ اول",
          quran: "قرآن",
          reader: "قراء",
          radio: "ریڈیو",
          live: "براہ راست",
          prayer: "نماز",
          sebha: "تسبیح",
          settings: "ترتیبات",
        },
      ],
      themes: [{ light: "روشن", simpledark: "تاریک", dark: "گہرا" }],
      icons: [{ styleOne: "آئیکن کا انداز ۱", styleTwo: "آئیکن کا انداز ۲" }],
      fonts: [
        {
          hafs: "حفص",
          qaloun: "قالون",
          nastaleeq: "نستعلیق",
          amiri: "العامری",
        },
      ],
      home: [
        {
          currentBookmarks: "موجودہ بُک مارکس",
          SurahFavorites: "پسندیدہ سورتیں",
        },
      ],
      quran: [
        {
          quranTitle: "قرآن پاک",
          searchPlaceHolder: "سورہ کے نام سے تلاش کریں",
          ayat: "آیات",
          numberOfAyahs: "آیات کی تعداد",
          surahOrder: "سورہ کی ترتیب",
          revelation: "نزول",
          revelationType1: "مکی",
          revelationType2: "مدنی",
          reading: "تلاوت",
          interpretation: "تفسیر",
          translation: "ترجمہ",
          listening: "سننا",
          alsurah: "سورہ",
          aljuz: "جز",
          alhizb: "حزب",
          alsafha: "صفحہ",
          ayah: "آیت",
          ayahPlay: "آیت چلائیں",
          ayahTafsier: "آیت کی تفسیر",
          ayahBookmark: "بک مارک",
          tafsierPlaceholder: "تفسیر منتخب کریں",
          translationPlaceholder: "ترجمہ منتخب کریں",
          translationButton: "ترجمہ دیکھیں",
          translationNotes: "ترجمہ منتخب کریں اور دیکھنے کے لئے کلک کریں",
        },
      ],
      readers: [
        {
          quranTitle: "قرآن",
          searchPlaceHolder: "قاری کے نام سے تلاش کریں",
          searchPlaceHolder2: "سورہ کے نام سے تلاش کریں",
          copyBtn: "سورہ کا لنک کاپی کریں",
          downloadBtn: "سورہ ڈاؤن لوڈ کریں",
          playBtn: "سورہ چلائیں",
        },
      ],
      radio: [{ quranTitle: "قرآن ریڈیو" }],
      tv: [{ quranTitle: "براہ راست قرآن" }],
      prayerTime: [
        {
          quranTitle: "نماز کے اوقات",
          gregorianDate: "گریگورین تاریخ",
          hijriDate: "ہجری تاریخ",
          month: "مہینہ",
          am: "صبح",
          pm: "شام",
          methods: ["طریقہ 1", "طریقہ 2", "طریقہ 3", "طریقہ 4", "طریقہ 5"],
          Fajr: "فجر",
          Sunrise: "طلوع آفتاب",
          Dhuhr: "ظہر",
          Asr: "عصر",
          Maghrib: "مغرب",
          Isha: "عشاء",
        },
      ],
      tasbeh: [
        {
          quranTitle: "تسبیح",
          buttonTasbehStart: "نماز کے بعد تسبیح شروع کریں",
          buttonTasbehStop: "نماز کے بعد تسبیح ختم کریں",
          tasbihLetters: ["سبحان اللہ", "الحمد للہ", "اللہ اکبر"],
        },
      ],
    },

    bn: {
      id: "bn",
      lang: "বাংলা",
      headerTitle: "কোরআন",
      navbar: [
        {
          home: "হোম",
          quran: "কুরআন",
          reader: "পাঠকবৃন্দ",
          radio: "রেডিও",
          live: "লাইভ",
          prayer: "নামাজ",
          sebha: "তাসবিহ",
          settings: "সেটিংস",
        },
      ],
      themes: [{ light: "আলোকিত", simpledark: "অন্ধকার", dark: "গভীর" }],
      icons: [{ styleOne: "আইকন শৈলী ১", styleTwo: "আইকন শৈলী ২" }],
      fonts: [
        {
          hafs: "হাফস",
          qaloun: "কালুন",
          nastaleeq: "নাস্তালিক",
          amiri: "আমিরি",
        },
      ],
      home: [
        {
          currentBookmarks: "বর্তমান বুকমার্ক",
          SurahFavorites: "প্রিয় সূরা",
        },
      ],
      quran: [
        {
          quranTitle: "কুরআন শরীফ",
          searchPlaceHolder: "সুরার নাম দিয়ে অনুসন্ধান করুন",
          ayat: "আয়াত",
          numberOfAyahs: "আয়াত সংখ্যা",
          surahOrder: "সুরার ক্রম",
          revelation: "উপলব্ধি",
          revelationType1: "মাক্কী",
          revelationType2: "মাদানী",
          reading: "পাঠ",
          interpretation: "তাফসির",
          translation: "অনুবাদ",
          listening: "শুনা",
          alsurah: "সুরা",
          aljuz: "জুজ",
          alhizb: "হিজব",
          alsafha: "পৃষ্ঠা",
          ayah: "আয়াত",
          ayahPlay: "আয়াত চালান",
          ayahTafsier: "আয়াতের তাফসির",
          ayahBookmark: "বুকমার্ক",
          tafsierPlaceholder: "তাফসির নির্বাচন করুন",
          translationPlaceholder: "অনুবাদ নির্বাচন করুন",
          translationButton: "অনুবাদ দেখুন",
          translationNotes: "অনুবাদ নির্বাচন করুন এবং দেখার জন্য ক্লিক করুন",
        },
      ],
      readers: [
        {
          quranTitle: "কোরআন",
          searchPlaceHolder: "পাঠকের নাম দ্বারা অনুসন্ধান করুন",
          searchPlaceHolder2: "সুরাহ নাম দ্বারা অনুসন্ধান করুন",
          copyBtn: "সূরা লিংক কপি করুন",
          downloadBtn: "সূরা ডাউনলোড করুন",
          playBtn: "সূরা প্লে করুন",
        },
      ],
      radio: [{ quranTitle: "কোরআন রেডিও" }],
      tv: [{ quranTitle: "সরাসরি কুরআন" }],
      prayerTime: [
        {
          quranTitle: "নামাজের সময়সূচী",
          gregorianDate: "গ্রেগরিয়ান তারিখ",
          hijriDate: "হিজরি তারিখ",
          month: "মাস",
          am: "এএম",
          pm: "পিএম",
          methods: ["পদ্ধতি ১", "পদ্ধতি ২", "পদ্ধতি ৩", "পদ্ধতি ৪", "পদ্ধতি ৫"],
          Fajr: "ফজর",
          Sunrise: "সূর্যোদয়",
          Dhuhr: "যোহর",
          Asr: "আসর",
          Maghrib: "মাগরিব",
          Isha: "ইশা",
        },
      ],
      tasbeh: [
        {
          quranTitle: "তাসবিহ",
          buttonTasbehStart: "নামাজের পরে তাসবিহ শুরু করুন",
          buttonTasbehStop: "নামাজের পরে তাসবিহ বন্ধ করুন",
          tasbihLetters: ["সুবহানআল্লাহ", "আলহামদুলিল্লাহ", "আল্লাহু আকবার"],
        },
      ],
    },

    bs: {
      id: "bs",
      lang: "Bosanski",
      headerTitle: "Kur'an",
      navbar: [
        {
          home: "Početna",
          quran: "Kuran",
          reader: "Čitači",
          radio: "Radio",
          live: "Uživo",
          prayer: "Molitva",
          sebha: "Tespih",
          settings: "Postavke",
        },
      ],
      themes: [{ light: "Svijetlo", simpledark: "Tamno", dark: "Tamno" }],
      icons: [{ styleOne: "Stil ikona 1", styleTwo: "Stil ikona 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Kalun",
          nastaleeq: "Nastalik",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Trenutne oznake",
          SurahFavorites: "Omiljene sure",
        },
      ],
      quran: [
        {
          quranTitle: "Kur'an",
          searchPlaceHolder: "Pretraži po nazivu sure",
          ayat: "Ajete",
          numberOfAyahs: "Broj ajeta",
          surahOrder: "Redoslijed sure",
          revelation: "Objava",
          revelationType1: "Mekanska",
          revelationType2: "Medinska",
          reading: "Čitanje",
          interpretation: "Tefsir",
          translation: "Prijevod",
          listening: "Slušanje",
          alsurah: "Sura",
          aljuz: "Džuz",
          alhizb: "Hizb",
          alsafha: "Stranica",
          ayah: "Ajet",
          ayahPlay: "Pusti ajet",
          ayahTafsier: "Tefsir ajeta",
          ayahBookmark: "Knjižna oznaka",
          tafsierPlaceholder: "Izaberite tefsir",
          translationPlaceholder: "Izaberite prijevod",
          translationButton: "Prikaži prijevod",
          translationNotes: "Izaberite prijevod i kliknite za prikaz",
        },
      ],
      readers: [
        {
          quranTitle: "Kur'an",
          searchPlaceHolder: "Traži po imenu učača",
          searchPlaceHolder2: "Traži po imenu sure",
          copyBtn: "Kopiraj poveznicu sura",
          downloadBtn: "Preuzmi suru",
          playBtn: "Reproduciraj suru",
        },
      ],
      radio: [{ quranTitle: "Kur'an Radio" }],
      tv: [{ quranTitle: "Kur'an uživo" }],
      prayerTime: [
        {
          quranTitle: "Vremena namaza",
          gregorianDate: "Gregorijanski datum",
          hijriDate: "Hidžretski datum",
          month: "Mjesec",
          am: "AM",
          pm: "PM",
          methods: ["Metoda 1", "Metoda 2", "Metoda 3", "Metoda 4", "Metoda 5"],
          Fajr: "Sabah",
          Sunrise: "Izlazak sunca",
          Dhuhr: "Podne",
          Asr: "Ikindija",
          Maghrib: "Akšam",
          Isha: "Jacija",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tesbih",
          buttonTasbehStart: "Započni Tesbih nakon namaza",
          buttonTasbehStop: "Završi Tesbih nakon namaza",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
    ug: {
      id: "ug",
      lang: "ئۇيغۇرچە",
      headerTitle: "قۇرئان",
      navbar: [
        {
          home: "باش بەت",
          quran: "قۇرئان",
          reader: "ئوقۇغۇچىلار",
          radio: "رادىئو",
          live: "توقۇمدا",
          prayer: "ناماز",
          sebha: "تەسبىھ",
          settings: "تۈزۈلمە",
        },
      ],
      themes: [{ light: "يېنىك", simpledark: "قاراڭغۇ", dark: "قاراڭغۇ" }],
      icons: [{ styleOne: "ئىكونا ئۇسۇلى 1", styleTwo: "ئىكونا ئۇسۇلى 2" }],
      fonts: [
        {
          hafs: "ھافس",
          qaloun: "قالۇن",
          nastaleeq: "ناستالىق",
          amiri: "ئامىرى",
        },
      ],
      home: [
        {
          currentBookmarks: "ھازىرقى بەلگىلەر",
          SurahFavorites: "ياخشى كۆرىدىغان سۈرە",
        },
      ],
      quran: [
        {
          quranTitle: "قۇرئان كەرىم",
          searchPlaceHolder: "سۈرە نامى بويىچە ئىزدەش",
          ayat: "ئاياتلار",
          numberOfAyahs: "ئايات سانى",
          surahOrder: "سۈرە تەرتىپى",
          revelation: "نازىل بولۇش",
          revelationType1: "مەكىيە",
          revelationType2: "مەدىنە",
          reading: "ئوقۇش",
          interpretation: "تەپسىر",
          translation: "تەرجىمە",
          listening: "تىڭشاش",
          alsurah: "سۈرە",
          aljuz: "جۈز",
          alhizb: "ھزب",
          alsafha: "بەت",
          ayah: "ئايات",
          ayahPlay: "ئاياتنى قويۇش",
          ayahTafsier: "ئاياتنىڭ تەپسىرى",
          ayahBookmark: "بەلگە",
          tafsierPlaceholder: "تەپسىر تاللاڭ",
          translationPlaceholder: "تەرجىمە تاللاڭ",
          translationButton: "تەرجىمىنى كۆرسىتىش",
          translationNotes: "تەرجىمە تاللاپ كۆرۈش ئۈچۈن چېكىڭ",
        },
      ],
      readers: [
        {
          quranTitle: "قۇرئان",
          searchPlaceHolder: "ئوقۇغۇچى نامى بىلەن ئىزدەش",
          searchPlaceHolder2: "سۈرى نامى بىلەن ئىزدەش",
          copyBtn: "سورا ئۇلىنىنى كاپىيىلەش",
          downloadBtn: "سورا چۈشۈرۈش",
          playBtn: "سورا پەيدا قىلىش",
        },
      ],
      radio: [{ quranTitle: "قۇرئان رادىيوسى" }],
      tv: [{ quranTitle: "تۆۋرە كۆرسەتكۈسى" }],
      prayerTime: [
        {
          quranTitle: "ناماز ۋاقىتلىرى",
          gregorianDate: "گريگورىي تارىخى",
          hijriDate: "ھىجرىيە تارىخى",
          month: "ئاي",
          am: "چۈشتىن بۇرۇن",
          pm: "چۈشتىن كېيىن",
          methods: ["ئۇسۇلى 1", "ئۇسۇلى 2", "ئۇسۇلى 3", "ئۇسۇلى 4", "ئۇسۇلى 5"],
          Fajr: "فەجر",
          Sunrise: "قۇياش چىقىشى",
          Dhuhr: "دۇھىر",
          Asr: "ئەسر",
          Maghrib: "مەغرىب",
          Isha: "ئىشا",
        },
      ],
      tasbeh: [
        {
          quranTitle: "تەسپیھ",
          buttonTasbehStart: "نامازدىن كېيىن تەسپیھ باشلاڭ",
          buttonTasbehStop: "نامازدىن كېيىن تەسپیھ توختىتىڭ",
          tasbihLetters: ["سۇبھان ئاللاھ", "ئەلھەمدۇ لىللاھ", "ئاللاھۇ ئەكبر"],
        },
      ],
    },

    fa: {
      id: "fa",
      lang: "فارسی",
      headerTitle: "قرآن",
      navbar: [
        {
          home: "خانه",
          quran: "قرآن",
          reader: "قاریان",
          radio: "رادیو",
          live: "پخش زنده",
          prayer: "نماز",
          sebha: "تسبیح",
          settings: "تنظیمات",
        },
      ],
      themes: [{ light: "روشن", simpledark: "تاریک", dark: "تاریک" }],
      icons: [{ styleOne: "سبک آیکون ۱", styleTwo: "سبک آیکون ۲" }],
      fonts: [
        { hafs: "حفص", qaloun: "قالون", nastaleeq: "نستعلیق", amiri: "عمری" },
      ],
      home: [
        {
          currentBookmarks: "نشانک‌های جاری",
          SurahFavorites: "سوره‌های مورد علاقه",
        },
      ],
      quran: [
        {
          quranTitle: "قرآن کریم",
          searchPlaceHolder: "جستجو با نام سوره",
          ayat: "آیات",
          numberOfAyahs: "تعداد آیات",
          surahOrder: "ترتیب سوره",
          revelation: "نزول",
          revelationType1: "مکی",
          revelationType2: "مدنی",
          reading: "خواندن",
          interpretation: "تفسیر",
          translation: "ترجمه",
          listening: "گوش دادن",
          alsurah: "سوره",
          aljuz: "جزء",
          alhizb: "حزب",
          alsafha: "صفحه",
          ayah: "آیه",
          ayahPlay: "پخش آیه",
          ayahTafsier: "تفسیر آیه",
          ayahBookmark: "نشانک",
          tafsierPlaceholder: "انتخاب تفسیر",
          translationPlaceholder: "انتخاب ترجمه",
          translationButton: "نمایش ترجمه",
          translationNotes: "ترجمه را انتخاب کرده و برای مشاهده کلیک کنید",
        },
      ],
      readers: [
        {
          quranTitle: "قرآن",
          searchPlaceHolder: "جستجو بر اساس نام قاری",
          searchPlaceHolder2: "جستجو بر اساس نام سوره",
          copyBtn: "کپی لینک سوره",
          downloadBtn: "دانلود سوره",
          playBtn: "پخش سوره",
        },
      ],
      radio: [{ quranTitle: "رادیو قرآن" }],
      tv: [{ quranTitle: "پخش زنده قرآن" }],
      prayerTime: [
        {
          quranTitle: "زمان نماز",
          gregorianDate: "تاریخ میلادی",
          hijriDate: "تاریخ هجری",
          month: "ماه",
          am: "صبح",
          pm: "عصر",
          methods: ["روش 1", "روش 2", "روش 3", "روش 4", "روش 5"],
          Fajr: "فجر",
          Sunrise: "طلوع آفتاب",
          Dhuhr: "ظهر",
          Asr: "عصر",
          Maghrib: "مغرب",
          Isha: "عشاء",
        },
      ],
      tasbeh: [
        {
          quranTitle: "تسبیح",
          buttonTasbehStart: "شروع تسبیح بعد از نماز",
          buttonTasbehStop: "پایان تسبیح بعد از نماز",
          tasbihLetters: ["سبحان الله", "الحمد لله", "الله اکبر"],
        },
      ],
    },
    tg: {
      id: "tg",
      lang: "Тоҷикӣ",
      headerTitle: "Қуръон",
      navbar: [
        {
          home: "Саҳифаи асосӣ",
          quran: "Қуръон",
          reader: "Қориён",
          radio: "Радио",
          live: "Пахши зинда",
          prayer: "Намоз",
          sebha: "Тасбеҳ",
          settings: "Танзимотҳо",
        },
      ],
      themes: [{ light: "Равшан", simpledark: "Торик", dark: "Торик" }],
      icons: [{ styleOne: "Стили иконка 1", styleTwo: "Стили иконка 2" }],
      fonts: [
        {
          hafs: "Ҳафс",
          qaloun: "Қалун",
          nastaleeq: "Настаълиқ",
          amiri: "Амири",
        },
      ],
      home: [
        {
          currentBookmarks: "Нишонҳои ҷорӣ",
          SurahFavorites: "Сураҳои дӯстдошта",
        },
      ],
      quran: [
        {
          quranTitle: "Қуръон",
          searchPlaceHolder: "Ҷустуҷӯ бо номи сура",
          ayat: "Оятҳо",
          numberOfAyahs: "Шумораи оятҳо",
          surahOrder: "Тартиби сура",
          revelation: "Нозилшавӣ",
          revelationType1: "Маккӣ",
          revelationType2: "Мадинӣ",
          reading: "Хондан",
          interpretation: "Тафсир",
          translation: "Тарҷума",
          listening: "Гӯш кардан",
          alsurah: "Сура",
          aljuz: "Ҷузъ",
          alhizb: "Ҳизб",
          alsafha: "Саҳифа",
          ayah: "Оят",
          ayahPlay: "Пахши оят",
          ayahTafsier: "Тафсири оят",
          ayahBookmark: "Аломат",
          tafsierPlaceholder: "Тафсирро интихоб кунед",
          translationPlaceholder: "Тарҷумаро интихоб кунед",
          translationButton: "Намоиши тарҷума",
          translationNotes:
            "Тарҷумаро интихоб кунед ва барои намоиш клик кунед",
        },
      ],
      readers: [
        {
          quranTitle: "Қуръон",
          searchPlaceHolder: "Ҷустуҷӯ бо номи хонанда",
          searchPlaceHolder2: "Ҷустуҷӯ бо номи Сура",
          copyBtn: "Копия пайванд сура",
          downloadBtn: "Файли сураро зеркашӣ кунед",
          playBtn: "Сураро навозед",
        },
      ],
      radio: [{ quranTitle: "Радиои Қуръон" }],
      tv: [{ quranTitle: "Қуръони зинда" }],
      prayerTime: [
        {
          quranTitle: "Вақти намоз",
          gregorianDate: "Санаи григорианӣ",
          hijriDate: "Санаи ҳиҷрӣ",
          month: "Моҳ",
          am: "Пеш аз нисфирӯзӣ",
          pm: "Баъд аз нисфирӯзӣ",
          methods: ["Усул 1", "Усул 2", "Усул 3", "Усул 4", "Усул 5"],
          Fajr: "Фаҷр",
          Sunrise: "Тулуи офтоб",
          Dhuhr: "Зуҳр",
          Asr: "Аср",
          Maghrib: "Маъғриб",
          Isha: "Ишо",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Тасбеҳ",
          buttonTasbehStart: "Оғози Тасбеҳ пас аз намоз",
          buttonTasbehStop: "Анҷоми Тасбеҳ пас аз намоз",
          tasbihLetters: ["Субҳаналлоҳ", "Алҳамдулиллоҳ", "Аллоҳу Акбар"],
        },
      ],
    },
    ml: {
      id: "ml",
      lang: "മലയാളം",
      headerTitle: "ഖുര്‍ആന്‍",
      navbar: [
        {
          home: "ഹോം",
          quran: "ഖുര്‍ആന്‍",
          reader: "വായനക്കാര്‍",
          radio: "റേഡിയോ",
          live: "തത്സമയം",
          prayer: "പ്രാര്‍ത്ഥന",
          sebha: "തസ്ബീഹ്",
          settings: "സജ്ജീകരണങ്ങൾ",
        },
      ],
      themes: [{ light: "വെളിച്ചം", simpledark: "ഇരുട്ട്", dark: "ഇരുട്ട്" }],
      icons: [{ styleOne: "ഐക്കൺ ശൈലി 1", styleTwo: "ഐക്കൺ ശൈലി 2" }],
      fonts: [
        {
          hafs: "ഹഫ്‌സ്",
          qaloun: "കല്ൌണ്‍",
          nastaleeq: "നസ്താലിഖ്",
          amiri: "അമിരി",
        },
      ],
      home: [
        {
          currentBookmarks: "നിലവിലെ ബുക്ക്മാർക്കുകൾ",
          SurahFavorites: "പ്രിയപ്പെട്ട സൂറകള്‍",
        },
      ],
      quran: [
        {
          quranTitle: "കുര്‍ആന്‍",
          searchPlaceHolder: "സൂരയുടെ പേരിൽ തിരയുക",
          ayat: "ആയാത്തുകൾ",
          numberOfAyahs: "ആയാത്തുകളുടെ എണ്ണം",
          surahOrder: "സൂരയുടെ ക്രമം",
          revelation: "പ്രകാശനം",
          revelationType1: "മക്കീ",
          revelationType2: "മദനീ",
          reading: "വായന",
          interpretation: "വ്യാഖ്യാനം",
          translation: "പരിഭാഷ",
          listening: "ശ്രവിക്കൽ",
          alsurah: "സൂര",
          aljuz: "ജുസ்",
          alhizb: "ഹിസ്‌ബ്",
          alsafha: "പേജ്",
          ayah: "ആയത്ത്",
          ayahPlay: "ആയത്ത് പ്ലേ ചെയ്യുക",
          ayahTafsier: "ആയത്തിന്റെ വ്യാഖ്യാനം",
          ayahBookmark: "ബുക്ക്മാർക്ക്",
          tafsierPlaceholder: "വ്യാഖ്യാനം തിരഞ്ഞെടുക്കുക",
          translationPlaceholder: "പരിഭാഷ തിരഞ്ഞെടുക്കുക",
          translationButton: "പരിഭാഷ കാണുക",
          translationNotes: "പരിഭാഷ തിരഞ്ഞെടുക്കുക, കാണാനായി ക്ലിക്ക് ചെയ്യുക",
        },
      ],
      readers: [
        {
          quranTitle: "ഖുര്‍ആന്‍",
          searchPlaceHolder: "പാരായകന്‍റെ പേര് ഉപയോഗിച്ച് തിരയുക",
          searchPlaceHolder2: "സൂരാഹ് പേര് ഉപയോഗിച്ച് തിരയുക",
          copyBtn: "സൂരയുടെ ലിങ്ക് പകര്‍പ്പുചെയ്യുക",
          downloadBtn: "സൂറ ഡൗൺലോഡ് ചെയ്യുക",
          playBtn: "സൂറ ചലിപ്പിക്കുക",
        },
      ],
      radio: [{ quranTitle: "ഖുര്‍ആന്‍ റേഡിയോ" }],
      tv: [{ quranTitle: "ലൈവ് ഖുര്‍ആന്‍" }],
      prayerTime: [
        {
          quranTitle: "പ്രാർത്ഥനയുടെ സമയം",
          gregorianDate: "ഗ്രിഗോറിയൻ തീയതി",
          hijriDate: "ഹിജ്റ തീയതി",
          month: "മാസം",
          am: "രാവിലെ",
          pm: "വൈകുന്നേരം",
          methods: ["രീതിയ 1", "രീതിയ 2", "രീതിയ 3", "രീതിയ 4", "രീതിയ 5"],
          Fajr: "ഫജർ",
          Sunrise: "സൂര്യോദയം",
          Dhuhr: "ദുഹർ",
          Asr: "അസർ",
          Maghrib: "മഗ്രിബ്",
          Isha: "ഇഷാ",
        },
      ],
      tasbeh: [
        {
          quranTitle: "തസ്‌ബീഹ്‌",
          buttonTasbehStart: "നമസ്കാരത്തിനു ശേഷം തസ്‌ബീഹ്‌ ആരംഭിക്കുക",
          buttonTasbehStop: "നമസ്കാരത്തിനു ശേഷം തസ്‌ബീഹ്‌ അവസാനിപ്പിക്കുക",
          tasbihLetters: [
            "സുഭാനല്ലാഹ്",
            "അല്‌ഹമ്ദുലില്ലാഹ്",
            "അല്ലാഹു അക്‌ബര്",
          ],
        },
      ],
    },
    tl: {
      id: "tl",
      lang: "Tagalog",
      headerTitle: "Quran",
      navbar: [
        {
          home: "Tahanan",
          quran: "Quran",
          reader: "Mga mambabasa",
          radio: "Radyo",
          live: "Live",
          prayer: "Panalangin",
          sebha: "Tasbih",
          settings: "Mga Setting",
        },
      ],
      themes: [{ light: "Maliwanag", simpledark: "Madilim", dark: "Madilim" }],
      icons: [{ styleOne: "Estilo ng Icon 1", styleTwo: "Estilo ng Icon 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Kasalukuyang mga Bookmark",
          SurahFavorites: "Mga Paboritong Surah",
        },
      ],
      quran: [
        {
          quranTitle: "Quran",
          searchPlaceHolder: "Maghanap gamit ang pangalan ng surah",
          ayat: "Mga Ayat",
          numberOfAyahs: "Bilang ng mga Ayat",
          surahOrder: "Pagkakasunod ng Surah",
          revelation: "Rebelasyon",
          revelationType1: "Makki",
          revelationType2: "Madani",
          reading: "Pagbabasa",
          interpretation: "Paliwanag",
          translation: "Pagsasalin",
          listening: "Pakikinig",
          alsurah: "Surah",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Pahina",
          ayah: "Ayah",
          ayahPlay: "I-play ang Ayah",
          ayahTafsier: "Paliwanag ng Ayah",
          ayahBookmark: "Bookmark",
          tafsierPlaceholder: "Pumili ng Paliwanag",
          translationPlaceholder: "Pumili ng Pagsasalin",
          translationButton: "Ipakita ang Pagsasalin",
          translationNotes: "Pumili ng Pagsasalin at i-click para makita",
        },
      ],
      readers: [
        {
          quranTitle: "Quran",
          searchPlaceHolder: "Maghanap ayon sa pangalan ng mambabasa",
          searchPlaceHolder2: "Maghanap ayon sa pangalan ng Surah",
          copyBtn: "Kopyahin ang Link ng Surah",
          downloadBtn: "I-download ang Surah",
          playBtn: "I-play ang Surah",
        },
      ],
      radio: [{ quranTitle: "Quran Radio" }],
      tv: [{ quranTitle: "Live Quran" }],
      prayerTime: [
        {
          quranTitle: "Oras ng Panalangin",
          gregorianDate: "Gregorian Date",
          hijriDate: "Hijri Date",
          month: "Buwan",
          am: "AM",
          pm: "PM",
          methods: ["Paraan 1", "Paraan 2", "Paraan 3", "Paraan 4", "Paraan 5"],
          Fajr: "Fajr",
          Sunrise: "Pagsikat ng Araw",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbeeh",
          buttonTasbehStart: "Simulan ang Tasbeeh pagkatapos ng Dasal",
          buttonTasbehStop: "Itigil ang Tasbeeh pagkatapos ng Dasal",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
    id: {
      id: "id",
      lang: "Bahasa Indonesia",
      headerTitle: "Qur'an",
      navbar: [
        {
          home: "Beranda",
          quran: "Quran",
          reader: "Pembaca",
          radio: "Radio",
          live: "Langsung",
          prayer: "Sholat",
          sebha: "Tasbih",
          settings: "Pengaturan",
        },
      ],
      themes: [{ light: "Terang", simpledark: "Gelap", dark: "Gelap" }],
      icons: [{ styleOne: "Gaya Ikon 1", styleTwo: "Gaya Ikon 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qalun",
          nastaleeq: "Nastaliq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Penanda Buku Saat Ini",
          SurahFavorites: "Surah Favorit",
        },
      ],
      quran: [
        {
          quranTitle: "Al-Quran",
          searchPlaceHolder: "Cari berdasarkan nama Surah",
          ayat: "Ayat",
          numberOfAyahs: "Jumlah Ayat",
          surahOrder: "Urutan Surah",
          revelation: "Wahyu",
          revelationType1: "Makkiyah",
          revelationType2: "Madaniyah",
          reading: "Membaca",
          interpretation: "Tafsir",
          translation: "Terjemahan",
          listening: "Mendengarkan",
          alsurah: "Surah",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Halaman",
          ayah: "Ayah",
          ayahPlay: "Putar Ayah",
          ayahTafsier: "Tafsir Ayah",
          ayahBookmark: "Penanda",
          tafsierPlaceholder: "Pilih Tafsir",
          translationPlaceholder: "Pilih Terjemahan",
          translationButton: "Tampilkan Terjemahan",
          translationNotes: "Pilih Terjemahan dan Klik untuk Melihat",
        },
      ],
      readers: [
        {
          quranTitle: "Qur'an",
          searchPlaceHolder: "Cari berdasarkan nama pembaca",
          searchPlaceHolder2: "Cari berdasarkan nama Surah",
          copyBtn: "Salin Tautan Surah",
          downloadBtn: "Unduh Surah",
          playBtn: "Putar Surah",
        },
      ],
      radio: [{ quranTitle: "Radio Quran" }],
      tv: [{ quranTitle: "Live Quran" }],
      prayerTime: [
        {
          quranTitle: "Waktu Salat",
          gregorianDate: "Tanggal Gregorian",
          hijriDate: "Tanggal Hijriah",
          month: "Bulan",
          am: "AM",
          pm: "PM",
          methods: ["Metode 1", "Metode 2", "Metode 3", "Metode 4", "Metode 5"],
          Fajr: "Fajr",
          Sunrise: "Matahari Terbit",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbih",
          buttonTasbehStart: "Mulai Tasbih setelah Sholat",
          buttonTasbehStop: "Hentikan Tasbih setelah Sholat",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
    pt: {
      id: "pt",
      lang: "Português",
      headerTitle: "Alcorão",
      navbar: [
        {
          home: "Início",
          quran: "Alcorão",
          reader: "Leitores",
          radio: "Rádio",
          live: "Ao vivo",
          prayer: "Oração",
          sebha: "Tasbih",
          settings: "Configurações",
        },
      ],
      themes: [{ light: "Claro", simpledark: "Escuro", dark: "Escuro" }],
      icons: [
        { styleOne: "Estilo de Ícones 1", styleTwo: "Estilo de Ícones 2" },
      ],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaleeq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Favoritos atuais",
          SurahFavorites: "Suras Favoritas",
        },
      ],
      quran: [
        {
          quranTitle: "Alcorão",
          searchPlaceHolder: "Pesquise pelo nome da Surata",
          ayat: "Versículos",
          numberOfAyahs: "Número de Versículos",
          surahOrder: "Ordem da Surata",
          revelation: "Revelação",
          revelationType1: "Mecano",
          revelationType2: "Medinense",
          reading: "Leitura",
          interpretation: "Interpretação",
          translation: "Tradução",
          listening: "Ouvir",
          alsurah: "Surata",
          aljuz: "Juz",
          alhizb: "Hizb",
          alsafha: "Página",
          ayah: "Versículo",
          ayahPlay: "Reproduzir Versículo",
          ayahTafsier: "Interpretação do Versículo",
          ayahBookmark: "Marcador",
          tafsierPlaceholder: "Escolher Interpretação",
          translationPlaceholder: "Escolher Tradução",
          translationButton: "Mostrar Tradução",
          translationNotes: "Escolha a Tradução e clique para ver",
        },
      ],
      readers: [
        {
          quranTitle: "Alcorão",
          searchPlaceHolder: "Pesquisar pelo nome do leitor",
          searchPlaceHolder2: "Pesquisar pelo nome da Surah",
          copyBtn: "Copiar Link da Surah",
          downloadBtn: "Baixar Surah",
          playBtn: "Tocar Surah",
        },
      ],
      radio: [{ quranTitle: "Rádio do Alcorão" }],
      tv: [{ quranTitle: "Alcorão ao Vivo" }],
      prayerTime: [
        {
          quranTitle: "Horários de Oração",
          gregorianDate: "Data Gregoriana",
          hijriDate: "Data Islâmica",
          month: "Mês",
          am: "AM",
          pm: "PM",
          methods: ["Método 1", "Método 2", "Método 3", "Método 4", "Método 5"],
          Fajr: "Fajr",
          Sunrise: "Nascer do Sol",
          Dhuhr: "Dhuhr",
          Asr: "Asr",
          Maghrib: "Maghrib",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbih",
          buttonTasbehStart: "Iniciar Tasbih após a Oração",
          buttonTasbehStop: "Parar Tasbih após a Oração",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
    ha: {
      id: "ha",
      lang: "Hausa",
      headerTitle: "Alkur'ani",
      navbar: [
        {
          home: "Gida",
          quran: "Al-Qur'ani",
          reader: "Makaranta",
          radio: "Rediyo",
          live: "Kai Tsaye",
          prayer: "Sallah",
          sebha: "Tasbihi",
          settings: "Saituna",
        },
      ],
      themes: [{ light: "Haske", simpledark: "Duƙaƙƙe", dark: "Duƙaƙƙe" }],
      icons: [{ styleOne: "Salon Alamar 1", styleTwo: "Salon Alamar 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Kalun",
          nastaleeq: "Nastaliq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Alamar Shafi Na Yanzu",
          SurahFavorites: "Suran Da Ake So",
        },
      ],
      quran: [
        {
          quranTitle: "Al-Qurani",
          searchPlaceHolder: "Bincike ta sunan Surah",
          ayat: "Ayoyi",
          numberOfAyahs: "Yawan Ayoyi",
          surahOrder: "Tsarin Surah",
          revelation: "Wahayin",
          revelationType1: "Makkiyya",
          revelationType2: "Madaniyya",
          reading: "Karatu",
          interpretation: "Tafsiri",
          translation: "Fassara",
          listening: "Sauraro",
          alsurah: "Surah",
          aljuz: "Juz'i",
          alhizb: "Hizb",
          alsafha: "Shafi",
          ayah: "Ayah",
          ayahPlay: "Saka Ayah",
          ayahTafsier: "Tafsirin Ayah",
          ayahBookmark: "Alamar Tuna",
          tafsierPlaceholder: "Zaɓi Tafsiri",
          translationPlaceholder: "Zaɓi Fassara",
          translationButton: "Nuna Fassara",
          translationNotes: "Zaɓi Fassara kuma danna don duba",
        },
      ],
      readers: [
        {
          quranTitle: "Alkur'ani",
          searchPlaceHolder: "Bincika da sunan mai karatu",
          searchPlaceHolder2: "Bincika da sunan surah",
          copyBtn: "Manna Link na Surah",
          downloadBtn: "Zazzage Surah",
          playBtn: "Buga Surah",
        },
      ],
      radio: [{ quranTitle: "Rediyon Alkurani" }],
      tv: [{ quranTitle: "Rayuwar Alkurani" }],
      prayerTime: [
        {
          quranTitle: "Lokutan Sallah",
          gregorianDate: "Kwanan wata na Gregorian",
          hijriDate: "Kwanan wata na Hijiri",
          month: "Wata",
          am: "Safiya",
          pm: "Yamma",
          methods: ["Hanya 1", "Hanya 2", "Hanya 3", "Hanya 4", "Hanya 5"],
          Fajr: "Fajr",
          Sunrise: "Fitowar Rana",
          Dhuhr: "Azahar",
          Asr: "La'asar",
          Maghrib: "Magriba",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbihi",
          buttonTasbehStart: "Fara Tasbihi bayan Sallah",
          buttonTasbehStop: "Dakatar da Tasbihi bayan Sallah",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
    sw: {
      id: "sw",
      lang: "Kiswahili",
      headerTitle: "Qurani",
      navbar: [
        {
          home: "Nyumbani",
          quran: "Qurani",
          reader: "Wasomaji",
          radio: "Redio",
          live: "Moja kwa moja",
          prayer: "Sala",
          sebha: "Tasbihi",
          settings: "Mipangilio",
        },
      ],
      themes: [{ light: "Nuru", simpledark: "Giza", dark: "Giza" }],
      icons: [{ styleOne: "Mtindo wa Ikoni 1", styleTwo: "Mtindo wa Ikoni 2" }],
      fonts: [
        {
          hafs: "Hafs",
          qaloun: "Qaloun",
          nastaleeq: "Nastaliq",
          amiri: "Amiri",
        },
      ],
      home: [
        {
          currentBookmarks: "Vitabu Vilivyowekwa Alama",
          SurahFavorites: "Sura Zilizopendwa",
        },
      ],
      quran: [
        {
          quranTitle: "Qurani",
          searchPlaceHolder: "Tafuta kwa jina la Surah",
          ayat: "Aya",
          numberOfAyahs: "Idadi ya Aya",
          surahOrder: "Mpangilio wa Surah",
          revelation: "Ufunuo",
          revelationType1: "Makki",
          revelationType2: "Madani",
          reading: "Kusoma",
          interpretation: "Tafsiri",
          translation: "Tafsiri",
          listening: "Kusikiliza",
          alsurah: "Surah",
          aljuz: "Juzuu",
          alhizb: "Hizb",
          alsafha: "Ukurasa",
          ayah: "Aya",
          ayahPlay: "Cheza Aya",
          ayahTafsier: "Tafsiri ya Aya",
          ayahBookmark: "Alama ya Kumbukumbu",
          tafsierPlaceholder: "Chagua Tafsiri",
          translationPlaceholder: "Chagua Tafsiri",
          translationButton: "Onyesha Tafsiri",
          translationNotes: "Chagua Tafsiri na Bonyeza ili Kuona",
        },
      ],
      readers: [
        {
          quranTitle: "Qurani",
          searchPlaceHolder: "Tafuta kwa jina la msomaji",
          searchPlaceHolder2: "Tafuta kwa jina la Surah",
          copyBtn: "Nakili Kiungo cha Surah",
          downloadBtn: "Pakua Surah",
          playBtn: "Piga Surah",
        },
      ],
      radio: [{ quranTitle: "Radio ya Qurani" }],
      tv: [{ quranTitle: "Qurani Moja kwa Moja" }],
      prayerTime: [
        {
          quranTitle: "Nyakati za Sala",
          gregorianDate: "Tarehe ya Gregori",
          hijriDate: "Tarehe ya Hijiria",
          month: "Mwezi",
          am: "Asubuhi",
          pm: "Jioni",
          methods: ["Njia 1", "Njia 2", "Njia 3", "Njia 4", "Njia 5"],
          Fajr: "Fajr",
          Sunrise: "Kuchomoza Jua",
          Dhuhr: "Adhuhuri",
          Asr: "Alasiri",
          Maghrib: "Magharibi",
          Isha: "Isha",
        },
      ],
      tasbeh: [
        {
          quranTitle: "Tasbihi",
          buttonTasbehStart: "Anza Tasbihi Baada ya Swala",
          buttonTasbehStop: "Komesha Tasbihi Baada ya Swala",
          tasbihLetters: ["SubhanAllah", "Alhamdulillah", "Allahu Akbar"],
        },
      ],
    },
  },
];
