export const surahApi = [
  {
    number: 1,
    name: {
      ar: "الفاتحة",
      eng: "Al Fatihah",
      fr: "Al Fatihah",
      es: "Al Fatiha",
      ur: "الفاتحہ",
      id: "Al Fatihah",
      ru: "Аль Фатиха",
      cn: "开端",
      de: "Die Eröffnung",
      pt: "A Abertura",
      th: "อัลฟาติฮะ",
      bn: "সূরা আল ফাতিহা",
      fa: "فاتحه",
      tr: "Fâtiha",
      bs: "Fatiha",
      ug: "ھافىس",
      tg: "Фотиҳа",
      ml: "അല് ഫാത്തിഹ",
      tl: "Al Fatihah",
      ha: "Al Fatihah",
      sw: "Al Fatihah",
    },
  },
  {
    number: 2,
    name: {
      ar: "البقرة",
      eng: "Al Baqarah",
      fr: "Al Baqarah",
      es: "Al Baqarah",
      ur: "البقرہ",
      id: "Al Baqarah",
      ru: "Аль Бакара",
      cn: "牛",
      de: "Die Kuh",
      pt: "A Vaca",
      th: "อัลบาการะฮ์",
      bn: "সূরা আল বাকারা",
      fa: "بقره",
      tr: "Bakara",
      bs: "Bakara",
      ug: "باقارا",
      tg: "Бақара",
      ml: "അല് ബഖറ",
      tl: "Al Baqarah",
      ha: "Al Baqarah",
      sw: "Al Baqarah",
    },
  },
  {
    number: 3,
    name: {
      ar: "آل عمران",
      eng: "Aal E Imran",
      fr: "Al Imran",
      es: "Al Imran",
      ur: "آل عمران",
      id: "Al Imran",
      ru: "Аль Имран",
      cn: "伊姆兰",
      de: "Die Familie Imran",
      pt: "A Família de Imran",
      th: "อาลอิมรอน",
      bn: "সূরা আলে ইমরান",
      fa: "آل عمران",
      tr: "Âl i İmrân",
      bs: "Imranova porodica",
      ug: "ئىميران ئائىلىسى",
      tg: "Оли Имрон",
      ml: "ആല് ഇംറാന്‍",
      tl: "Al Imran",
      ha: "Al Imran",
      sw: "Aal E Imran",
    },
  },
  {
    number: 4,
    name: {
      ar: "النساء",
      eng: "An Nisa",
      fr: "An Nisa",
      es: "An Nisa",
      ur: "النساء",
      id: "An Nisa",
      ru: "Ан Ниса",
      cn: "妇女",
      de: "Die Frauen",
      pt: "As Mulheres",
      th: "อันนิซาอ์",
      bn: "সূরা আন নিসা",
      fa: "نساء",
      tr: "Nisâ",
      bs: "Nisa",
      ug: "ئانىسا",
      tg: "Нисо",
      ml: "അല് നിസ",
      tl: "An Nisa",
      ha: "An Nisa",
      sw: "An Nisa",
    },
  },
  {
    number: 5,
    name: {
      ar: "المائدة",
      eng: "Al Ma'idah",
      fr: "Al Ma'idah",
      es: "Al Ma'idah",
      ur: "المائدہ",
      id: "Al Maidah",
      ru: "Аль Маида",
      cn: "筵席",
      de: "Der Tisch",
      pt: "A Mesa",
      th: "อัลมาอิดะห์",
      bn: "সূরা আল মায়েদা",
      fa: "مائده",
      tr: "Mâide",
      bs: "Maide",
      ug: "مائىدە",
      tg: "Моид",
      ml: "അല് മായിദ",
      tl: "Al Ma'idah",
      ha: "Al Ma'idah",
      sw: "Al Ma'idah",
    },
  },
  {
    number: 6,
    name: {
      ar: "الأنعام",
      eng: "Al An'am",
      fr: "Al An'am",
      es: "Al An'am",
      ur: "الانعام",
      id: "Al An'am",
      ru: "Аль Анам",
      cn: "牲畜",
      de: "Das Vieh",
      pt: "O Gado",
      th: "อัลอันอาม",
      bn: "সূরা আল আনআম",
      fa: "انعام",
      tr: "En'âm",
      bs: "En'am",
      ug: "ئەنئام",
      tg: "Анъом",
      ml: "അല് അനം",
      tl: "Al An'am",
      ha: "Al An'am",
      sw: "Al An'am",
    },
  },
  {
    number: 7,
    name: {
      ar: "الأعراف",
      eng: "Al A'raf",
      fr: "Al A'raf",
      es: "Al A'raf",
      ur: "الاعراف",
      id: "Al A'raf",
      ru: "Аль Араф",
      cn: "高处",
      de: "Die Höhen",
      pt: "Os Lugares Elevados",
      th: "อัลอะอฺรอฟ",
      bn: "সূরা আল আ'রাফ",
      fa: "اعراف",
      tr: "A'râf",
      bs: "Araf",
      ug: "ئاراپ",
      tg: "Аъроф",
      ml: "അല് അറാഫ്",
      tl: "Al A'raf",
      ha: "Al A'raf",
      sw: "Al A'raf",
    },
  },
  {
    number: 8,
    name: {
      ar: "الأنفال",
      eng: "Al Anfal",
      fr: "Al Anfal",
      es: "Al Anfal",
      ur: "الانفال",
      id: "Al Anfal",
      ru: "Аль Анфаль",
      cn: "战利品",
      de: "Die Beute",
      pt: "Os Espólios",
      th: "อัลอันফาล",
      bn: "সূরা আল আনফাল",
      fa: "انفال",
      tr: "Enfâl",
      bs: "Anfal",
      ug: "ئەنفال",
      tg: "Анфол",
      ml: "അല് അന്‍ഫാല്‍",
      tl: "Al Anfal",
      ha: "Al Anfal",
      sw: "Al Anfal",
    },
  },
  {
    number: 9,
    name: {
      ar: "التوبة",
      eng: "At Tawbah",
      fr: "At Tawbah",
      es: "At Tawbah",
      ur: "التوبہ",
      id: "At Tawbah",
      ru: "Ат Тауба",
      cn: "忏悔",
      de: "Die Reue",
      pt: "O Arrependimento",
      th: "อัตเตาบะฮ์",
      bn: "সূরা আত তাওবা",
      fa: "توبه",
      tr: "Tevbe",
      bs: "Tevba",
      ug: "تەۋبە",
      tg: "Тавба",
      ml: "അല് തൌബ",
      tl: "At Tawbah",
      ha: "At Tawbah",
      sw: "At Tawbah",
    },
  },
  {
    number: 10,
    name: {
      ar: "يونس",
      eng: "Yunus",
      fr: "Yunus",
      es: "Yunus",
      ur: "یونس",
      id: "Yunus",
      ru: "Юнус",
      cn: "优努斯",
      de: "Jonas",
      pt: "Jonas",
      th: "ยูนุส",
      bn: "সূরা ইউনুস",
      fa: "یونس",
      tr: "Yûnus",
      bs: "Junus",
      ug: "يۇنۇس",
      tg: "Юнус",
      ml: "യൂനുസ്",
      tl: "Yunus",
      ha: "Yunus",
      sw: "Yunus",
    },
  },

  {
    number: 11,
    name: {
      ar: "هود",
      eng: "Hud",
      fr: "Hud",
      es: "Hud",
      ur: "ہود",
      id: "Hud",
      ru: "Худ",
      cn: "胡德",
      de: "Hud",
      pt: "Hud",
      th: "ฮุด",
      bn: "সূরা হুদ",
      fa: "هود",
      tr: "Hûd",
      bs: "Hud",
      ug: "ھود",
      tg: "Ҳуд",
      ml: "ഹൂദ്",
      tl: "Hud",
      ha: "Hud",
      sw: "Hud",
    },
  },
  {
    number: 12,
    name: {
      ar: "يوسف",
      eng: "Yusuf",
      fr: "Yusuf",
      es: "Yusuf",
      ur: "یوسف",
      id: "Yusuf",
      ru: "Юсуф",
      cn: "优素福",
      de: "Joseph",
      pt: "José",
      th: "ยูซฟ",
      bn: "সূরা ইউসুফ",
      fa: "یوسف",
      tr: "Yûsuf",
      bs: "Jusuf",
      ug: "يۇسۇپ",
      tg: "Юсуф",
      ml: "യൂസഫ്",
      tl: "Yusuf",
      ha: "Yusuf",
      sw: "Yusuf",
    },
  },
  {
    number: 13,
    name: {
      ar: "الرعد",
      eng: "Ar Ra'd",
      fr: "Ar Ra'd",
      es: "Ar Ra'd",
      ur: "الرعد",
      id: "Ar Ra'd",
      ru: "Ар Рад",
      cn: "雷",
      de: "Der Donner",
      pt: "O Trovão",
      th: "อัลเราะด",
      bn: "সূরা আর রাদ",
      fa: "رعد",
      tr: "Ra'd",
      bs: "Grom",
      ug: "رعد",
      tg: "Раъд",
      ml: "അല് റഅദ്",
      tl: "Ar Ra'd",
      ha: "Ar Ra'd",
      sw: "Ar Ra'd",
    },
  },
  {
    number: 14,
    name: {
      ar: "إبراهيم",
      eng: "Ibrahim",
      fr: "Ibrahim",
      es: "Ibrahim",
      ur: "ابراہیم",
      id: "Ibrahim",
      ru: "Ибрагим",
      cn: "易卜拉欣",
      de: "Ibrahim",
      pt: "Ibrahim",
      th: "อิบราฮิม",
      bn: "সূরা ইব্রাহিম",
      fa: "ابراهیم",
      tr: "İbrahim",
      bs: "Ibrahim",
      ug: "ئابراھىم",
      tg: "Иброҳим",
      ml: "ഇബ്രാഹിം",
      tl: "Ibrahim",
      ha: "Ibrahim",
      sw: "Ibrahim",
    },
  },
  {
    number: 15,
    name: {
      ar: "الحجر",
      eng: "Al Hijr",
      fr: "Al Hijr",
      es: "Al Hijr",
      ur: "الحجر",
      id: "Al Hijr",
      ru: "Хиджр",
      cn: "石头",
      de: "Der Felsen",
      pt: "A Rocha",
      th: "อัลฮิจร์",
      bn: "সূরা হিজর",
      fa: "حجر",
      tr: "Hicr",
      bs: "Hidžr",
      ug: "ھىجر",
      tg: "Ҳиджр",
      ml: "അല് ഹിജ്ര",
      tl: "Al Hijr",
      ha: "Al Hijr",
      sw: "Al Hijr",
    },
  },
  {
    number: 16,
    name: {
      ar: "النحل",
      eng: "An Nahl",
      fr: "An Nahl",
      es: "An Nahl",
      ur: "النحل",
      id: "An Nahl",
      ru: "Ан Нахль",
      cn: "蜜蜂",
      de: "Die Biene",
      pt: "As Abelhas",
      th: "อัลนحل",
      bn: "সূরা আন নحل",
      fa: "نحل",
      tr: "Nahl",
      bs: "Pčela",
      ug: "بۇغداي",
      tg: "Нахл",
      ml: "അല് നഹ്ൽ",
      tl: "An Nahl",
      ha: "An Nahl",
      sw: "An Nahl",
    },
  },
  {
    number: 17,
    name: {
      ar: "الإسراء",
      eng: "Al Isra",
      fr: "Al Isra",
      es: "Al Isra",
      ur: "الإسراء",
      id: "Al Isra",
      ru: "Исра",
      cn: "夜行",
      de: "Die Nachtreise",
      pt: "A Viagem Noturna",
      th: "อัลอิสรา",
      bn: "সূরা ইসরা",
      fa: "اسراء",
      tr: "İsra",
      bs: "Isra",
      ug: "ئسرا",
      tg: "Исро",
      ml: "അല് ഇസ്രാ",
      tl: "Al Isra",
      ha: "Al Isra",
      sw: "Al Isra",
    },
  },
  {
    number: 18,
    name: {
      ar: "الكهف",
      eng: "Al Kahf",
      fr: "Al Kahf",
      es: "Al Kahf",
      ur: "الکہف",
      id: "Al Kahf",
      ru: "Аль Кахф",
      cn: "洞穴",
      de: "Die Höhle",
      pt: "A Caverna",
      th: "อัลกะฮ์ฟ",
      bn: "সূরা আল কাহف",
      fa: "كهف",
      tr: "Kehf",
      bs: "Kahf",
      ug: "كەھف",
      tg: "Каҳф",
      ml: "അല് കഹ്फ़",
      tl: "Al Kahf",
      ha: "Al Kahf",
      sw: "Al Kahf",
    },
  },
  {
    number: 19,
    name: {
      ar: "مريم",
      eng: "Maryam",
      fr: "Maryam",
      es: "Maryam",
      ur: "مریم",
      id: "Maryam",
      ru: "Мариям",
      cn: "玛利亚",
      de: "Maria",
      pt: "Maria",
      th: "แมรีย์ام",
      bn: "সূরা মেরিয়ম",
      fa: "مریم",
      tr: "Meryem",
      bs: "Merjem",
      ug: "مەرۋى",
      tg: "Марям",
      ml: "മറിയം",
      tl: "Maryam",
      ha: "Maryam",
      sw: "Maryam",
    },
  },
  {
    number: 20,
    name: {
      ar: "طه",
      eng: "Taha",
      fr: "Taha",
      es: "Taha",
      ur: "طه",
      id: "Taha",
      ru: "Таха",
      cn: "塔哈",
      de: "Taha",
      pt: "Taha",
      th: "ตอฮา",
      bn: "সূরা তহা",
      fa: "طه",
      tr: "Tâhâ",
      bs: "Taha",
      ug: "طەها",
      tg: "Тоҳо",
      ml: "താഹാ",
      tl: "Taha",
      ha: "Taha",
      sw: "Taha",
    },
  },

  {
    number: 21,
    name: {
      ar: "الأنبياء",
      eng: "Al Anbiya",
      fr: "Al Anbiya",
      es: "Al Anbiya",
      ur: "الانبیاء",
      id: "Al Anbiya",
      ru: "Аль Анбиа",
      cn: "先知",
      de: "Die Propheten",
      pt: "Os Profetas",
      th: "อัลอันบิยา",
      bn: "সূরা আল আনবিয়া",
      fa: "انبیاء",
      tr: "Enbiyâ",
      bs: "Anbija",
      ug: "ئەنبىيە",
      tg: "Анбиё",
      ml: "അല് അംബിയاء",
      tl: "Al Anbiya",
      ha: "Al Anbiya",
      sw: "Al Anbiya",
    },
  },
  {
    number: 22,
    name: {
      ar: "الحج",
      eng: "Al Hajj",
      fr: "Al Hajj",
      es: "Al Hajj",
      ur: "الحج",
      id: "Al Hajj",
      ru: "Хадж",
      cn: "朝觐",
      de: "Die Pilgerfahrt",
      pt: "A Peregrinação",
      th: "อัลฮัจ",
      bn: "সূরা الحج",
      fa: "حج",
      tr: "Hac",
      bs: "Hajj",
      ug: "ھاج",
      tg: "Ҳадж",
      ml: "അല് ഹജ്ജ്",
      tl: "Al Hajj",
      ha: "Al Hajj",
      sw: "Al Hajj",
    },
  },
  {
    number: 23,
    name: {
      ar: "المؤمنون",
      eng: "Al Mu'minun",
      fr: "Al Mu'minun",
      es: "Al Mu'minun",
      ur: "المؤمنون",
      id: "Al Mu'minun",
      ru: "Муминун",
      cn: "信士",
      de: "Die Gläubigen",
      pt: "Os Crentes",
      th: "อัลมุؤمنون",
      bn: "সূরা আল মুমিনুন",
      fa: "مؤمنون",
      tr: "Müminler",
      bs: "Mumin",
      ug: "مؤمنون",
      tg: "Мӯъминун",
      ml: "അല് മു‍മിനുന്",
      tl: "Al Mu'minun",
      ha: "Al Mu'minun",
      sw: "Al Mu'minun",
    },
  },
  {
    number: 24,
    name: {
      ar: "النور",
      eng: "An Nur",
      fr: "An Nur",
      es: "An Nur",
      ur: "النور",
      id: "An Nur",
      ru: "Ан Нур",
      cn: "光明",
      de: "Das Licht",
      pt: "A Luz",
      th: "อัลนูร",
      bn: "সূরা আন নূর",
      fa: "نور",
      tr: "Nur",
      bs: "Nur",
      ug: "نور",
      tg: "Нур",
      ml: "അല് നൂര്",
      tl: "An Nur",
      ha: "An Nur",
      sw: "An Nur",
    },
  },
  {
    number: 25,
    name: {
      ar: "الفرقان",
      eng: "Al Furqan",
      fr: "Al Furqan",
      es: "Al Furqan",
      ur: "الفرقان",
      id: "Al Furqan",
      ru: "Аль Фуркан",
      cn: "判断",
      de: "Der Unterschied",
      pt: "O Critério",
      th: "อัลฟุรกาน",
      bn: "সূরা আল ফুরqan",
      fa: "فرقان",
      tr: "Furkan",
      bs: "Furkan",
      ug: "فرقان",
      tg: "Фурқан",
      ml: "അല് ഫുർഖാൻ",
      tl: "Al Furqan",
      ha: "Al Furqan",
      sw: "Al Furqan",
    },
  },
  {
    number: 26,
    name: {
      ar: "الشعراء",
      eng: "Ash Shu'ara",
      fr: "Ash Shu'ara",
      es: "Ash Shu'ara",
      ur: "الشعراء",
      id: "Ash Shu'ara",
      ru: "Аш Шуара",
      cn: "诗人",
      de: "Die Dichter",
      pt: "Os Poetas",
      th: "อัชนุอ์",
      bn: "সূরা আশ শুআরা",
      fa: "شعراء",
      tr: "Şuara",
      bs: "Šuara",
      ug: "شعرا",
      tg: "Шуъара",
      ml: "അല് ഷൂعراء",
      tl: "Ash Shu'ara",
      ha: "Ash Shu'ara",
      sw: "Ash Shu'ara",
    },
  },
  {
    number: 27,
    name: {
      ar: "النمل",
      eng: "An Naml",
      fr: "An Naml",
      es: "An Naml",
      ur: "النمل",
      id: "An Naml",
      ru: "Ан Намль",
      cn: "蚂蚁",
      de: "Die Ameisen",
      pt: "As Formigas",
      th: "อัลนัมล",
      bn: "সূরা আন নমল",
      fa: "نمل",
      tr: "Neml",
      bs: "Namal",
      ug: "نمل",
      tg: "Намл",
      ml: "അല് നമല്",
      tl: "An Naml",
      ha: "An Naml",
      sw: "An Naml",
    },
  },
  {
    number: 28,
    name: {
      ar: "القصص",
      eng: "Al Qasas",
      fr: "Al Qasas",
      es: "Al Qasas",
      ur: "القصص",
      id: "Al Qasas",
      ru: "Аль Касас",
      cn: "故事",
      de: "Die Geschichten",
      pt: "As Histórias",
      th: "อัลกะซัซ",
      bn: "সূরা আল কাসাস",
      fa: "قصص",
      tr: "Kasas",
      bs: "Kasas",
      ug: "قصص",
      tg: "Қасас",
      ml: "അല് കസസ്",
      tl: "Al Qasas",
      ha: "Al Qasas",
      sw: "Al Qasas",
    },
  },
  {
    number: 29,
    name: {
      ar: "العنكبوت",
      eng: "Al Ankabut",
      fr: "Al Ankabut",
      es: "Al Ankabut",
      ur: "العنكبوت",
      id: "Al Ankabut",
      ru: "Аль Анкабут",
      cn: "蜘蛛",
      de: "Die Spinne",
      pt: "A Aranha",
      th: "อัลอันกาบุต",
      bn: "সূরা আল আنكাবوت",
      fa: "عنکبوت",
      tr: "Ankebut",
      bs: "Pavuk",
      ug: "ئانكاۋت",
      tg: "Анкабут",
      ml: "അല് അങ്കബूत",
      tl: "Al Ankabut",
      ha: "Al Ankabut",
      sw: "Al Ankabut",
    },
  },
  {
    number: 30,
    name: {
      ar: "الروم",
      eng: "Ar Rum",
      fr: "Ar Rum",
      es: "Ar Rum",
      ur: "الروم",
      id: "Ar Rum",
      ru: "Аль Рум",
      cn: "罗马",
      de: "Die Römer",
      pt: "Os Romanos",
      th: "อัลรูม",
      bn: "সূরা আর রূম",
      fa: "روم",
      tr: "Rum",
      bs: "Rim",
      ug: "رۇم",
      tg: "Рум",
      ml: "അല് റൂം",
      tl: "Ar Rum",
      ha: "Ar Rum",
      sw: "Ar Rum",
    },
  },
  {
    number: 31,
    name: {
      ar: "لقمان",
      eng: "Luqman",
      fr: "Luqman",
      es: "Luqman",
      ur: "لقمان",
      id: "Luqman",
      ru: "Лукман",
      cn: "卢克曼",
      de: "Luqman",
      pt: "Luqmân",
      th: "อัลลุกมัน",
      bn: "সূরা লুকমান",
      fa: "لقمان",
      tr: "Lokman",
      bs: "Lukman",
      ug: "لوقمان",
      tg: "Луқмон",
      ml: "അല് ലഖمان്",
      tl: "Luqman",
      ha: "Luqman",
      sw: "Luqman",
    },
  },
  {
    number: 32,
    name: {
      ar: "السجدة",
      eng: "As Sajda",
      fr: "As Sajda",
      es: "As Sajda",
      ur: "السجدة",
      id: "As Sajda",
      ru: "Ас Саджа",
      cn: "叩拜",
      de: "Die Niederwerfung",
      pt: "A Prostração",
      th: "อัลซัจดะ",
      bn: "সূরা আস সাজদাহ",
      fa: "سجده",
      tr: "Secde",
      bs: "Sedad",
      ug: "سجدە",
      tg: "Сажда",
      ml: "അല് സജ്ദة",
      tl: "As Sajda",
      ha: "As Sajda",
      sw: "As Sajda",
    },
  },
  {
    number: 33,
    name: {
      ar: "الأحزاب",
      eng: "Al Ahzab",
      fr: "Al Ahzab",
      es: "Al Ahzab",
      ur: "الأحزاب",
      id: "Al Ahzab",
      ru: "Аль Ахзаб",
      cn: "同盟",
      de: "Die Gruppen",
      pt: "Os Partidos",
      th: "อัลอัซฮาบ",
      bn: "সূরা আল احزاب",
      fa: "احزاب",
      tr: "Ahzab",
      bs: "Ahzab",
      ug: "احزاب",
      tg: "Аҳзоб",
      ml: "അല് അഹزاب്",
      tl: "Al Ahzab",
      ha: "Al Ahzab",
      sw: "Al Ahzab",
    },
  },
  {
    number: 34,
    name: {
      ar: "سبأ",
      eng: "Saba",
      fr: "Saba",
      es: "Saba",
      ur: "سبأ",
      id: "Saba",
      ru: "Саба",
      cn: "萨巴",
      de: "Saba",
      pt: "Sabá",
      th: "อัลซาบา",
      bn: "সূরা সাবা",
      fa: "سبا",
      tr: "Sebe",
      bs: "Saba",
      ug: "سەبا",
      tg: "Сабо",
      ml: "അല് സബأ",
      tl: "Saba",
      ha: "Saba",
      sw: "Saba",
    },
  },
  {
    number: 35,
    name: {
      ar: "فاطر",
      eng: "Fatir",
      fr: "Fatir",
      es: "Fatir",
      ur: "فاطر",
      id: "Fatir",
      ru: "Фатир",
      cn: "创造者",
      de: "Der Schöpfer",
      pt: "O Criador",
      th: "อัลฟاطر",
      bn: "সূরা ফাতির",
      fa: "فاطر",
      tr: "Fatır",
      bs: "Fâtır",
      ug: "فاتىر",
      tg: "Фатир",
      ml: "അല് ഫാസിർ",
      tl: "Fatir",
      ha: "Fatir",
      sw: "Fatir",
    },
  },
  {
    number: 36,
    name: {
      ar: "يس",
      eng: "Ya Sin",
      fr: "Ya Sin",
      es: "Ya Sin",
      ur: "يس",
      id: "Ya Sin",
      ru: "Ясин",
      cn: "耶辛",
      de: "Ya Sin",
      pt: "Ya Sin",
      th: "ยาซีน",
      bn: "সূরা ইয়াসীন",
      fa: "یس",
      tr: "Yasin",
      bs: "Yasin",
      ug: "يس",
      tg: "Йасин",
      ml: "അല് യാസീൻ",
      tl: "Ya Sin",
      ha: "Ya Sin",
      sw: "Ya Sin",
    },
  },
  {
    number: 37,
    name: {
      ar: "الصافات",
      eng: "As Saffat",
      fr: "As Saffat",
      es: "As Saffat",
      ur: "الصافات",
      id: "As Saffat",
      ru: "Ас Саффат",
      cn: "排列",
      de: "Die Aufreihenden",
      pt: "Os Que Se Alinham",
      th: "อัลซาฟات",
      bn: "সূরা আস صافات",
      fa: "صافات",
      tr: "Safat",
      bs: "Saffat",
      ug: "صافات",
      tg: "Саффат",
      ml: "അല് സഫാത്ത്",
      tl: "As Saffat",
      ha: "As Saffat",
      sw: "As Saffat",
    },
  },
  {
    number: 38,
    name: {
      ar: "ص",
      eng: "Sad",
      fr: "Sad",
      es: "Sad",
      ur: "ص",
      id: "Sad",
      ru: "Сад",
      cn: "萨德",
      de: "Sad",
      pt: "Sad",
      th: "ซาด",
      bn: "সূরা সাদ",
      fa: "ص",
      tr: "Sad",
      bs: "Sad",
      ug: "ص",
      tg: "Сад",
      ml: "അല് സാദ്",
      tl: "Sad",
      ha: "Sad",
      sw: "Sad",
    },
  },
  {
    number: 39,
    name: {
      ar: "الزمر",
      eng: "Az Zumar",
      fr: "Az Zumar",
      es: "Az Zumar",
      ur: "الزمر",
      id: "Az Zumar",
      ru: "Аль Зумар",
      cn: "众群",
      de: "Die Gruppen",
      pt: "Os Grupos",
      th: "อัลซุมَر",
      bn: "সূরা আয যুমার",
      fa: "زمر",
      tr: "Zümer",
      bs: "Zumer",
      ug: "زمر",
      tg: "Зумар",
      ml: "അല് അസ്വര്",
      tl: "Az Zumar",
      ha: "Az Zumar",
      sw: "Az Zumar",
    },
  },
  {
    number: 40,
    name: {
      ar: "غافر",
      eng: "Ghafir",
      fr: "Ghafir",
      es: "Ghafir",
      ur: "غافر",
      id: "Ghafir",
      ru: "Гафар",
      cn: "宽恕者",
      de: "Der Vergebende",
      pt: "O Perdoador",
      th: "อัลغาฟِر",
      bn: "সূরা গাফির",
      fa: "غافر",
      tr: "Gafur",
      bs: "Gafir",
      ug: "غافر",
      tg: "Ғофир",
      ml: "അല് ഘാഫര്",
      tl: "Ghafir",
      ha: "Ghafir",
      sw: "Ghafir",
    },
  },
  {
    number: 41,
    name: {
      ar: "فصلت",
      eng: "Fussilat",
      fr: "Fussilat",
      es: "Fussilat",
      ur: "فصلت",
      id: "Fussilat",
      ru: "Фуссилат",
      cn: "详细",
      de: "Die Ausführliche",
      pt: "A Que Foi Explicada",
      th: "อัลฟุصلัต",
      bn: "সূরা ফصّلت",
      fa: "فصلت",
      tr: "Fussilet",
      bs: "Fussilat",
      ug: "فصلت",
      tg: "Фусилат",
      ml: "അല് ഫസ്‌ലത്",
      tl: "Fussilat",
      ha: "Fussilat",
      sw: "Fussilat",
    },
  },
  {
    number: 42,
    name: {
      ar: "الشورى",
      eng: "Ash Shura",
      fr: "Ash Shura",
      es: "Ash Shura",
      ur: "الشورى",
      id: "Ash Shura",
      ru: "Аш Шура",
      cn: "协商",
      de: "Die Beratung",
      pt: "A Consultação",
      th: "อัลชูรา",
      bn: "সূরা আল শুরى",
      fa: "شوری",
      tr: "Şura",
      bs: "Şura",
      ug: "شورى",
      tg: "Шура",
      ml: "അല് ഷൂറാ",
      tl: "Ash Shura",
      ha: "Ash Shura",
      sw: "Ash Shura",
    },
  },
  {
    number: 43,
    name: {
      ar: "الزخرف",
      eng: "Az Zukhruf",
      fr: "Az Zukhruf",
      es: "Az Zukhruf",
      ur: "الزخرف",
      id: "Az Zukhruf",
      ru: "Аз Зухруф",
      cn: "装饰",
      de: "Die Zierde",
      pt: "A Ornamentação",
      th: "อัลซุخرف",
      bn: "সূরা আয ਜ਼خرف",
      fa: "زخرف",
      tr: "Zukhruf",
      bs: "Zukhruf",
      ug: "زخرف",
      tg: "Зухруф",
      ml: "അല് സുഖ്രഫ്",
      tl: "Az Zukhruf",
      ha: "Az Zukhruf",
      sw: "Az Zukhruf",
    },
  },
  {
    number: 44,
    name: {
      ar: "الدخان",
      eng: "Ad Dukhan",
      fr: "Ad Dukhan",
      es: "Ad Dukhan",
      ur: "الدخان",
      id: "Ad Dukhan",
      ru: "Ад Духан",
      cn: "烟雾",
      de: "Der Rauch",
      pt: "A Fumaça",
      th: "อัลดุخان",
      bn: "সূরা আল দخان",
      fa: "دخان",
      tr: "Duhan",
      bs: "Duhan",
      ug: "دخان",
      tg: "Духон",
      ml: "അല് ദুখാൻ",
      tl: "Ad Dukhan",
      ha: "Ad Dukhan",
      sw: "Ad Dukhan",
    },
  },
  {
    number: 45,
    name: {
      ar: "الجاثية",
      eng: "Al Jathiya",
      fr: "Al Jathiya",
      es: "Al Jathiya",
      ur: "الجاثية",
      id: "Al Jathiya",
      ru: "Аль Джасия",
      cn: "跪下",
      de: "Die Knieende",
      pt: "A Que Se Prostra",
      th: "อัลญาธية",
      bn: "সূرا আল جاثية",
      fa: "جاثية",
      tr: "Casi",
      bs: "Al Jathiya",
      ug: "جاثية",
      tg: "Ҷасия",
      ml: "അല് ജത്തി",
      tl: "Al Jathiya",
      ha: "Al Jathiya",
      sw: "Al Jathiya",
    },
  },
  {
    number: 46,
    name: {
      ar: "الأحقاف",
      eng: "Al Ahqaf",
      fr: "Al Ahqaf",
      es: "Al Ahqaf",
      ur: "الأحقاف",
      id: "Al Ahqaf",
      ru: "Аль Ахкаф",
      cn: "阿赫卡夫",
      de: "Die Sanddünen",
      pt: "As Dunas",
      th: "อัลอักาฟ",
      bn: "সূরা আল احقاف",
      fa: "احقاف",
      tr: "Ahkaf",
      bs: "Ahkaf",
      ug: "احقاف",
      tg: "Аҳқоф",
      ml: "അല് അഹقാഫ്",
      tl: "Al Ahqaf",
      ha: "Al Ahqaf",
      sw: "Al Ahqaf",
    },
  },
  {
    number: 47,
    name: {
      ar: "محمد",
      eng: "Muhammad",
      fr: "Muhammad",
      es: "Muhammad",
      ur: "محمد",
      id: "Muhammad",
      ru: "Мухаммад",
      cn: "穆罕默德",
      de: "Muhammad",
      pt: "Muhammad",
      th: "มุฮัมมัด",
      bn: "সূরা মুহাম্মদ",
      fa: "محمد",
      tr: "Muhammed",
      bs: "Muhammed",
      ug: "محمد",
      tg: "Муҳаммад",
      ml: "അല് മുഹമ്മദ്",
      tl: "Muhammad",
      ha: "Muhammad",
      sw: "Muhammad",
    },
  },
  {
    number: 48,
    name: {
      ar: "الفتح",
      eng: "Al Fath",
      fr: "Al Fath",
      es: "Al Fath",
      ur: "الفتح",
      id: "Al Fath",
      ru: "Аль Фатх",
      cn: "胜利",
      de: "Der Sieg",
      pt: "A Vitória",
      th: "อัลฟتح",
      bn: "সূরা আল فتح",
      fa: "فتح",
      tr: "Fetih",
      bs: "Fetih",
      ug: "فتح",
      tg: "Фатҳ",
      ml: "അല് ഫത്ത്",
      tl: "Al Fath",
      ha: "Al Fath",
      sw: "Al Fath",
    },
  },
  {
    number: 49,
    name: {
      ar: "الحجرات",
      eng: "Al Hujurat",
      fr: "Al Hujurat",
      es: "Al Hujurat",
      ur: "الحجرات",
      id: "Al Hujurat",
      ru: "Аль Худжрат",
      cn: "房间",
      de: "Die Gemächer",
      pt: "Os Apartamentos",
      th: "อัลหุญุราต",
      bn: "সূরা الحجرات",
      fa: "حجرات",
      tr: "Hucurat",
      bs: "Hucurat",
      ug: "الحجرات",
      tg: "Худрат",
      ml: "അല് ഹുജുറത്",
      tl: "Al Hujurat",
      ha: "Al Hujurat",
      sw: "Al Hujurat",
    },
  },
  {
    number: 50,
    name: {
      ar: "ق",
      eng: "Qaf",
      fr: "Qaf",
      es: "Qaf",
      ur: "ق",
      id: "Qaf",
      ru: "Каф",
      cn: "卡夫",
      de: "Qaf",
      pt: "Qaf",
      th: "คาฟ",
      bn: "সূরা ক্বাফ",
      fa: "ق",
      tr: "Kaf",
      bs: "Kaf",
      ug: "ق",
      tg: "Қаф",
      ml: "അല് കാഫ",
      tl: "Qaf",
      ha: "Qaf",
      sw: "Qaf",
    },
  },
  {
    number: 51,
    name: {
      ar: "الذاريات",
      eng: "Adh Dhariyat",
      fr: "Adh Dhariyat",
      es: "Adh Dhariyat",
      ur: "الذاريات",
      id: "Adh Dhariyat",
      ru: "Ад Дариат",
      cn: "风",
      de: "Die Winde",
      pt: "Os Ventos",
      th: "อัลซอเรียت",
      bn: "সূরা আল ذاريات",
      fa: "ذاریات",
      tr: "Zariyat",
      bs: "Dharijat",
      ug: "ذاريات",
      tg: "Дариёт",
      ml: "അല് അധ ദاريات",
      tl: "Adh Dhariyat",
      ha: "Adh Dhariyat",
      sw: "Adh Dhariyat",
    },
  },
  {
    number: 52,
    name: {
      ar: "الطور",
      eng: "At Tur",
      fr: "At Tur",
      es: "At Tur",
      ur: "الطور",
      id: "At Tur",
      ru: "Ат Тур",
      cn: "土",
      de: "Der Berg",
      pt: "O Monte",
      th: "อัลตูร์",
      bn: "সূরা আল طور",
      fa: "طور",
      tr: "Tur",
      bs: "Tur",
      ug: "طور",
      tg: "Тур",
      ml: "അല് തൂർ",
      tl: "At Tur",
      ha: "At Tur",
      sw: "At Tur",
    },
  },
  {
    number: 53,
    name: {
      ar: "النجم",
      eng: "An Najm",
      fr: "An Najm",
      es: "An Najm",
      ur: "النجم",
      id: "An Najm",
      ru: "Ан Наджм",
      cn: "星",
      de: "Der Stern",
      pt: "A Estrela",
      th: "อัลนجم",
      bn: "সূরা النجم",
      fa: "نجم",
      tr: "Necm",
      bs: "Necm",
      ug: "نجم",
      tg: "Нажм",
      ml: "അല് നജ്മ്",
      tl: "An Najm",
      ha: "An Najm",
      sw: "An Najm",
    },
  },
  {
    number: 54,
    name: {
      ar: "القمر",
      eng: "Al Qamar",
      fr: "Al Qamar",
      es: "Al Qamar",
      ur: "القمر",
      id: "Al Qamar",
      ru: "Аль Камар",
      cn: "月",
      de: "Der Mond",
      pt: "A Lua",
      th: "อัลกามر",
      bn: "সূরা القمر",
      fa: "قمر",
      tr: "Kamer",
      bs: "Kamer",
      ug: "قمر",
      tg: "Қамар",
      ml: "അല് ഖമർ",
      tl: "Al Qamar",
      ha: "Al Qamar",
      sw: "Al Qamar",
    },
  },
  {
    number: 55,
    name: {
      ar: "الرحمن",
      eng: "Ar Rahman",
      fr: "Ar Rahman",
      es: "Ar Rahman",
      ur: "الرحمن",
      id: "Ar Rahman",
      ru: "Ар Рахман",
      cn: "至仁",
      de: "Der Allerbarmer",
      pt: "O Misericordioso",
      th: "อัลเราะห์มาน",
      bn: "সূরা الرحمن",
      fa: "رحمن",
      tr: "Rahman",
      bs: "Rahman",
      ug: "رحمن",
      tg: "Раҳмон",
      ml: "അല് റഹ്മാൻ",
      tl: "Ar Rahman",
      ha: "Ar Rahman",
      sw: "Ar Rahman",
    },
  },
  {
    number: 56,
    name: {
      ar: "الواقعـة",
      eng: "Al Waqi'a",
      fr: "Al Waqi'a",
      es: "Al Waqi'a",
      ur: "الواقعـة",
      id: "Al Waqi'a",
      ru: "Аль Вакиа",
      cn: "现实",
      de: "Das Unausweichliche",
      pt: "O Dia do Juízo",
      th: "อัลวากعة",
      bn: "সূرا الوقعه",
      fa: "واقع",
      tr: "Vaki'a",
      bs: "Vaki'a",
      ug: "واقع",
      tg: "Вақиа",
      ml: "അല് വാഖعة",
      tl: "Al Waqi'a",
      ha: "Al Waqi'a",
      sw: "Al Waqi'a",
    },
  },
  {
    number: 57,
    name: {
      ar: "الحديد",
      eng: "Al Hadid",
      fr: "Al Hadid",
      es: "Al Hadid",
      ur: "الحديد",
      id: "Al Hadid",
      ru: "Аль Хадид",
      cn: "铁",
      de: "Das Eisen",
      pt: "O Ferro",
      th: "อัลฮะดีد",
      bn: "সূরা আল حديد",
      fa: "حدید",
      tr: "Hadid",
      bs: "Hadid",
      ug: "حديد",
      tg: "Ҳадид",
      ml: "അല് ഹദീദ്",
      tl: "Al Hadid",
      ha: "Al Hadid",
      sw: "Al Hadid",
    },
  },
  {
    number: 58,
    name: {
      ar: "المجادلة",
      eng: "Al Mujadila",
      fr: "Al Mujadila",
      es: "Al Mujadila",
      ur: "المجادلة",
      id: "Al Mujadila",
      ru: "Аль Муджадила",
      cn: "争论",
      de: "Die Streitende",
      pt: "A Contendedora",
      th: "อัลมุญาดิลา",
      bn: "সূরা المجادلة",
      fa: "مجادلة",
      tr: "Mücadele",
      bs: "Mücadila",
      ug: "مجادلة",
      tg: "Муджалид",
      ml: "അല് മുജാദില",
      tl: "Al Mujadila",
      ha: "Al Mujadila",
      sw: "Al Mujadila",
    },
  },
  {
    number: 59,
    name: {
      ar: "الحشر",
      eng: "Al Hashr",
      fr: "Al Hashr",
      es: "Al Hashr",
      ur: "الحشر",
      id: "Al Hashr",
      ru: "Аль Хашр",
      cn: "集合",
      de: "Die Versammlung",
      pt: "A Assembleia",
      th: "อัลฮัชร์",
      bn: "সূرا الحشر",
      fa: "حشر",
      tr: "Haşr",
      bs: "Haşr",
      ug: "حشر",
      tg: "Ҳашр",
      ml: "അല് ഹഷർ",
      tl: "Al Hashr",
      ha: "Al Hashr",
      sw: "Al Hashr",
    },
  },
  {
    number: 60,
    name: {
      ar: "الممتحنة",
      eng: "Al Mumtahana",
      fr: "Al Mumtahana",
      es: "Al Mumtahana",
      ur: "الممتحنة",
      id: "Al Mumtahana",
      ru: "Аль Мумтахина",
      cn: "考试",
      de: "Die Prüfende",
      pt: "A Testadora",
      th: "อัลมุมتحنة",
      bn: "সূরা الممتحنة",
      fa: "ممتحنة",
      tr: "Mümtehane",
      bs: "Mümtehane",
      ug: "ممتحنة",
      tg: "Мумтахина",
      ml: "അല് മംتحنة",
      tl: "Al Mumtahana",
      ha: "Al Mumtahana",
      sw: "Al Mumtahana",
    },
  },
  {
    number: 61,
    name: {
      ar: "الصف",
      eng: "As Saff",
      fr: "As Saff",
      es: "As Saff",
      ur: "الصف",
      id: "As Saff",
      ru: "Ас Сафф",
      cn: "行列",
      de: "Die Reihe",
      pt: "A Fileira",
      th: "อัลซัฟ",
      bn: "সূرا الصف",
      fa: "صف",
      tr: "Saff",
      bs: "Saff",
      ug: "صف",
      tg: "Сафф",
      ml: "അല് സഫ",
      tl: "As Saff",
      ha: "As Saff",
      sw: "As Saff",
    },
  },
  {
    number: 62,
    name: {
      ar: "الجمعة",
      eng: "Al Jumua",
      fr: "Al Jumua",
      es: "Al Jumua",
      ur: "الجمعة",
      id: "Al Jumua",
      ru: "Аль Джумуа",
      cn: "星期五",
      de: "Der Freitag",
      pt: "A Sexta feira",
      th: "อัลญุมعة",
      bn: "সূرا الجمعة",
      fa: "جمعه",
      tr: "Cuma",
      bs: "Cuma",
      ug: "جمعه",
      tg: "Ҷумъа",
      ml: "അല് ജുമعة",
      tl: "Al Jumua",
      ha: "Al Jumua",
      sw: "Al Jumua",
    },
  },
  {
    number: 63,
    name: {
      ar: "المنافقون",
      eng: "Al Munafiqun",
      fr: "Al Munafiqun",
      es: "Al Munafiqun",
      ur: "المنافقون",
      id: "Al Munafiqun",
      ru: "Аль Мунафика",
      cn: "伪信士",
      de: "Die Heuchler",
      pt: "Os Hipócritas",
      th: "อัลมุนาฟِقُونَ",
      bn: "সূرا المنافقون",
      fa: "منافقون",
      tr: "Münafıklar",
      bs: "Munafiqun",
      ug: "منافقون",
      tg: "Мунафиқун",
      ml: "അല് മുനാഫقൂൺ",
      tl: "Al Munafiqun",
      ha: "Al Munafiqun",
      sw: "Al Munafiqun",
    },
  },
  {
    number: 64,
    name: {
      ar: "التغابن",
      eng: "At Taghabun",
      fr: "At Taghabun",
      es: "At Taghabun",
      ur: "التغابن",
      id: "At Taghabun",
      ru: "Аль Тагхабун",
      cn: "交易",
      de: "Der Betrug",
      pt: "A Enganação",
      th: "อัลตักฮาบุน",
      bn: "সূرا التغابن",
      fa: "تغابن",
      tr: "Tegabun",
      bs: "Tegabun",
      ug: "تغابن",
      tg: "Тагҳабун",
      ml: "അല് തഘابون",
      tl: "At Taghabun",
      ha: "At Taghabun",
      sw: "At Taghabun",
    },
  },
  {
    number: 65,
    name: {
      ar: "الطلاق",
      eng: "At Talaq",
      fr: "At Talaq",
      es: "At Talaq",
      ur: "الطلاق",
      id: "At Talaq",
      ru: "Аль Талак",
      cn: "离婚",
      de: "Die Scheidung",
      pt: "O Divórcio",
      th: "อัลตะล๊าก",
      bn: "সূرا الطلاق",
      fa: "طلاق",
      tr: "Talak",
      bs: "Talak",
      ug: "طلاق",
      tg: "Талак",
      ml: "അല് തലाक",
      tl: "At Talaq",
      ha: "At Talaq",
      sw: "At Talaq",
    },
  },
  {
    number: 66,
    name: {
      ar: "التحريم",
      eng: "At Tahrim",
      fr: "At Tahrim",
      es: "At Tahrim",
      ur: "التحريم",
      id: "At Tahrim",
      ru: "Аль Тахрим",
      cn: "禁忌",
      de: "Das Verbot",
      pt: "A Proibição",
      th: "อัลตะฮฺรีม",
      bn: "সূরা التحريم",
      fa: "تحریم",
      tr: "Tahrim",
      bs: "Tahrim",
      ug: "تحریم",
      tg: "Таҳрим",
      ml: "അല് തഹ്രീം",
      tl: "At Tahrim",
      ha: "At Tahrim",
      sw: "At Tahrim",
    },
  },
  {
    number: 67,
    name: {
      ar: "الملك",
      eng: "Al Mulk",
      fr: "Al Mulk",
      es: "Al Mulk",
      ur: "الملك",
      id: "Al Mulk",
      ru: "Аль Мульк",
      cn: "王",
      de: "Die Herrschaft",
      pt: "A Soberania",
      th: "อัลมุลك",
      bn: "সূرا الملك",
      fa: "ملک",
      tr: "Mulk",
      bs: "Mulk",
      ug: "ملک",
      tg: "Мулк",
      ml: "അല് മُلْك",
      tl: "Al Mulk",
      ha: "Al Mulk",
      sw: "Al Mulk",
    },
  },
  {
    number: 68,
    name: {
      ar: "القلم",
      eng: "Al Qalam",
      fr: "Al Qalam",
      es: "Al Qalam",
      ur: "القلم",
      id: "Al Qalam",
      ru: "Аль Калам",
      cn: "笔",
      de: "Der Stift",
      pt: "A Caneta",
      th: "อัลกาลัม",
      bn: "সূরা القلم",
      fa: "قلم",
      tr: "Kalem",
      bs: "Kalem",
      ug: "قلم",
      tg: "Қалам",
      ml: "അല് ഖَلَم",
      tl: "Al Qalam",
      ha: "Al Qalam",
      sw: "Al Qalam",
    },
  },
  {
    number: 69,
    name: {
      ar: "الحاقة",
      eng: "Al Haaqqa",
      fr: "Al Haaqqa",
      es: "Al Haaqqa",
      ur: "الحاقة",
      id: "Al Haaqqa",
      ru: "Аль Хаакка",
      cn: "真实",
      de: "Das Unvermeidliche",
      pt: "A Verdadeira",
      th: "อัลฮากะ",
      bn: "সূرا الحاقة",
      fa: "حاقه",
      tr: "Hakka",
      bs: "Hakka",
      ug: "حاقه",
      tg: "Ҳақиқат",
      ml: "അല് الحَاقَة",
      tl: "Al Haaqqa",
      ha: "Al Haaqqa",
      sw: "Al Haaqqa",
    },
  },
  {
    number: 70,
    name: {
      ar: "المعارج",
      eng: "Al Ma'arij",
      fr: "Al Ma'arij",
      es: "Al Ma'arij",
      ur: "المعارج",
      id: "Al Ma'arij",
      ru: "Аль Мааридж",
      cn: "升天",
      de: "Die Stufen",
      pt: "As Escadas",
      th: "อัลมอะอารีج",
      bn: "সূরা المعارج",
      fa: "معارج",
      tr: "Ma'arij",
      bs: "Ma'arij",
      ug: "معارج",
      tg: "Маъаридж",
      ml: "അല് المَعَارِج",
      tl: "Al Ma'arij",
      ha: "Al Ma'arij",
      sw: "Al Ma'arij",
    },
  },
  {
    number: 71,
    name: {
      ar: "نوح",
      eng: "Nuh",
      fr: "Nuh",
      es: "Nuh",
      ur: "نوح",
      id: "Nuh",
      ru: "Нух",
      cn: "努哈",
      de: "Noah",
      pt: "Noé",
      th: "นูฮฺ",
      bn: "সূরা نُوح",
      fa: "نوح",
      tr: "Nuh",
      bs: "Nuh",
      ug: "نوح",
      tg: "Нӯҳ",
      ml: "അല് നُوح",
      tl: "Nuh",
      ha: "Nuh",
      sw: "Nuh",
    },
  },
  {
    number: 72,
    name: {
      ar: "الجن",
      eng: "Al Jinn",
      fr: "Al Jinn",
      es: "Al Jinn",
      ur: "الجن",
      id: "Al Jinn",
      ru: "Аль Джинн",
      cn: "精灵",
      de: "Die Dschinn",
      pt: "Os Gênios",
      th: "อัลญิน",
      bn: "সূرا الجن",
      fa: "جن",
      tr: "Cin",
      bs: "Džin",
      ug: "جن",
      tg: "Джин",
      ml: "അല് ജിന്ന്",
      tl: "Al Jinn",
      ha: "Al Jinn",
      sw: "Al Jinn",
    },
  },
  {
    number: 73,
    name: {
      ar: "المزمل",
      eng: "Al Muzzammil",
      fr: "Al Muzzammil",
      es: "Al Muzzammil",
      ur: "المزمل",
      id: "Al Muzzammil",
      ru: "Аль Муззаммиль",
      cn: "包袱",
      de: "Der Eingehüllte",
      pt: "O Envolto",
      th: "อัลมุซซัมมิล",
      bn: "সূরা المزمل",
      fa: "مزمل",
      tr: "Müzzemmil",
      bs: "Muzzammil",
      ug: "مزمل",
      tg: "Муззаммиль",
      ml: "അല് المُزَّمِّل",
      tl: "Al Muzzammil",
      ha: "Al Muzzammil",
      sw: "Al Muzzammil",
    },
  },
  {
    number: 74,
    name: {
      ar: "المدثر",
      eng: "Al Muddathir",
      fr: "Al Muddathir",
      es: "Al Muddathir",
      ur: "المدثر",
      id: "Al Muddathir",
      ru: "Аль Муддассир",
      cn: "包裹",
      de: "Der Überhüllte",
      pt: "O Envolto",
      th: "อัลมุดษํริร",
      bn: "সূরা المدثر",
      fa: "مدثر",
      tr: "Müddessir",
      bs: "Muddathir",
      ug: "مدثر",
      tg: "Муддассир",
      ml: "അല് المُدَّثِّر",
      tl: "Al Muddathir",
      ha: "Al Muddathir",
      sw: "Al Muddathir",
    },
  },
  {
    number: 75,
    name: {
      ar: "القيامة",
      eng: "Al Qiyamah",
      fr: "Al Qiyamah",
      es: "Al Qiyamah",
      ur: "القيامة",
      id: "Al Qiyamah",
      ru: "Аль Кийама",
      cn: "复活",
      de: "Die Auferstehung",
      pt: "A Ressurreição",
      th: "อัลกิยามة",
      bn: "সূرا القيامة",
      fa: "قیامت",
      tr: "Kıyamet",
      bs: "Kıyamet",
      ug: "قیامت",
      tg: "Қиёмат",
      ml: "അല് القِيَامَة",
      tl: "Al Qiyamah",
      ha: "Al Qiyamah",
      sw: "Al Qiyamah",
    },
  },
  {
    number: 76,
    name: {
      ar: "الإنسان",
      eng: "Al Insan",
      fr: "Al Insan",
      es: "Al Insan",
      ur: "الإنسان",
      id: "Al Insan",
      ru: "Аль Инсан",
      cn: "人",
      de: "Der Mensch",
      pt: "O Homem",
      th: "อัลอีนซาน",
      bn: "সূরা الإنسان",
      fa: "انسان",
      tr: "İnsan",
      bs: "Insan",
      ug: "انسان",
      tg: "Инсон",
      ml: "അല് إنسان",
      tl: "Al Insan",
      ha: "Al Insan",
      sw: "Al Insan",
    },
  },
  {
    number: 77,
    name: {
      ar: "المرسلات",
      eng: "Al Mursalat",
      fr: "Al Mursalat",
      es: "Al Mursalat",
      ur: "المرسلات",
      id: "Al Mursalat",
      ru: "Аль Мурсалат",
      cn: "派遣者",
      de: "Die Gesandten",
      pt: "Os Enviados",
      th: "อัลมุรซาลات",
      bn: "সূرا المرسلات",
      fa: "مرسلات",
      tr: "Mürselat",
      bs: "Mürselat",
      ug: "المرسلات",
      tg: "Марсалат",
      ml: "അല് المُرْسَلَات",
      tl: "Al Mursalat",
      ha: "Al Mursalat",
      sw: "Al Mursalat",
    },
  },
  {
    number: 78,
    name: {
      ar: "النبأ",
      eng: "An Naba",
      fr: "An Naba",
      es: "An Naba",
      ur: "النبأ",
      id: "An Naba",
      ru: "Ан Наба",
      cn: "消息",
      de: "Die Nachricht",
      pt: "A Notícia",
      th: "อัลนาบأ",
      bn: "সূرا النبأ",
      fa: "نبأ",
      tr: "Neba",
      bs: "Neba",
      ug: "نبأ",
      tg: "Набъа",
      ml: "അല് النَّبَأ",
      tl: "An Naba",
      ha: "An Naba",
      sw: "An Naba",
    },
  },
  {
    number: 79,
    name: {
      ar: "النازعات",
      eng: "An Nazi'at",
      fr: "An Nazi'at",
      es: "An Nazi'at",
      ur: "النازعات",
      id: "An Nazi'at",
      ru: "Ан Нази'ат",
      cn: "驱逐者",
      de: "Die Zerrenden",
      pt: "As Arrancadoras",
      th: "อัลนาซีعات",
      bn: "সূরা النازعات",
      fa: "نازعات",
      tr: "Nazi'at",
      bs: "Nazi'at",
      ug: "نازعات",
      tg: "Нозият",
      ml: "അل نازِعَات",
      tl: "An Nazi'at",
      ha: "An Nazi'at",
      sw: "An Nazi'at",
    },
  },
  {
    number: 80,
    name: {
      ar: "عبس",
      eng: "Abasa",
      fr: "Abasa",
      es: "Abasa",
      ur: "عبس",
      id: "Abasa",
      ru: "Абаса",
      cn: "皱眉",
      de: "Er hat die Stirn gerunzelt",
      pt: "Abasa",
      th: "อับس",
      bn: "সূرا عبس",
      fa: "عبس",
      tr: "Abese",
      bs: "Abasa",
      ug: "عبس",
      tg: "Абас",
      ml: "അل عَبَسَ",
      tl: "Abasa",
      ha: "Abasa",
      sw: "Abasa",
    },
  },
  {
    number: 81,
    name: {
      ar: "التكوير",
      eng: "At Takwir",
      fr: "At Takwir",
      es: "At Takwir",
      ur: "التكوير",
      id: "At Takwir",
      ru: "Ат Таквир",
      cn: "卷",
      de: "Das Einhüllen",
      pt: "A Envolvência",
      th: "อัลตะควิร์",
      bn: "সূرا التكوير",
      fa: "تکویری",
      tr: "Takwir",
      bs: "Takwir",
      ug: "التكوير",
      tg: "Таквир",
      ml: "അല് التَّكْوِير",
      tl: "At Takwir",
      ha: "At Takwir",
      sw: "At Takwir",
    },
  },
  {
    number: 82,
    name: {
      ar: "الانفطار",
      eng: "Al Infitar",
      fr: "Al Infitar",
      es: "Al Infitar",
      ur: "الانفطار",
      id: "Al Infitar",
      ru: "Аль Инфитар",
      cn: "破裂",
      de: "Die Spaltung",
      pt: "A Fissura",
      th: "อัลอิฟطار",
      bn: "সূরা الانفطار",
      fa: "انفطار",
      tr: "İnfitar",
      bs: "İnfitar",
      ug: "انفطار",
      tg: "Инфитар",
      ml: "അل الإِنفِطَار",
      tl: "Al Infitar",
      ha: "Al Infitar",
      sw: "Al Infitar",
    },
  },

  {
    number: 83,
    name: {
      ar: "المطففين",
      eng: "Al Mutaffifin",
      fr: "Al Mutaffifin",
      es: "Al Mutaffifin",
      ur: "المطففين",
      id: "Al Mutaffifin",
      ru: "Аль Мутаффифин",
      cn: "作弊者",
      de: "Die Betrüger",
      pt: "Os Fraudeadores",
      th: "อัลมุตาฟฟِفين",
      bn: "সূরা المطففين",
      fa: "مطففین",
      tr: "Mutaffifin",
      bs: "Mutaffifin",
      ug: "مطففین",
      tg: "Мутаффифин",
      ml: "അല് മുതഫ്ഫിഫിന്",
      tl: "Al Mutaffifin",
      ha: "Al Mutaffifin",
      sw: "Al Mutaffifin",
    },
  },

  {
    number: 84,
    name: {
      ar: "الإنشقاق",
      eng: "Al Inshiqaq",
      fr: "Al Inshiqaq",
      es: "Al Inshiqaq",
      ur: "الإنشقاق",
      id: "Al Inshiqaq",
      ru: "Аль Иншикак",
      cn: "裂开",
      de: "Die Spaltung",
      pt: "A Fenda",
      th: "อัลอินชิการ",
      bn: "সূরা الإنشقاق",
      fa: "انشقاق",
      tr: "İnşikak",
      bs: "Inshiqaq",
      ug: "انشقاق",
      tg: "Иншиқоқ",
      ml: "അല് ഇൻഷِقَاق",
      tl: "Al Inshiqaq",
      ha: "Al Inshiqaq",
      sw: "Al Inshiqaq",
    },
  },
  {
    number: 85,
    name: {
      ar: "البروج",
      eng: "Al Burooj",
      fr: "Al Burooj",
      es: "Al Burooj",
      ur: "البروج",
      id: "Al Burooj",
      ru: "Аль Бурудж",
      cn: "星座",
      de: "Die Türme",
      pt: "As Constelações",
      th: "อัลบูรุج",
      bn: "সূরা البروج",
      fa: "بروج",
      tr: "Buruc",
      bs: "Buruc",
      ug: "بروج",
      tg: "Буруҷ",
      ml: "അല് البُرُوج",
      tl: "Al Burooj",
      ha: "Al Burooj",
      sw: "Al Burooj",
    },
  },
  {
    number: 86,
    name: {
      ar: "التكاثر",
      eng: "At Takathur",
      fr: "At Takathur",
      es: "At Takathur",
      ur: "التكاثر",
      id: "At Takathur",
      ru: "Ат Таксур",
      cn: "过多",
      de: "Das Mehran",
      pt: "A Multiplicação",
      th: "อัลตะคاثُر",
      bn: "সূরা التكاثر",
      fa: "تکاثر",
      tr: "Tekasür",
      bs: "Tekasür",
      ug: "تكاثر",
      tg: "Такосур",
      ml: "അല് التَّكَاثُر",
      tl: "At Takathur",
      ha: "At Takathur",
      sw: "At Takathur",
    },
  },
  {
    number: 87,
    name: {
      ar: "الأعلى",
      eng: "Al A'la",
      fr: "Al A'la",
      es: "Al A'la",
      ur: "الأعلى",
      id: "Al A'la",
      ru: "Аль А'ла",
      cn: "最高",
      de: "Der Höchste",
      pt: "O Altíssimo",
      th: "อัลอา'لا",
      bn: "সূরা الأعلى",
      fa: "اعلی",
      tr: "A'la",
      bs: "A'la",
      ug: "الأعلى",
      tg: "Аъла",
      ml: "അല് الأَعْلَى",
      tl: "Al A'la",
      ha: "Al A'la",
      sw: "Al A'la",
    },
  },
  {
    number: 88,
    name: {
      ar: "الغاشية",
      eng: "Al Ghashiyah",
      fr: "Al Ghashiyah",
      es: "Al Ghashiyah",
      ur: "الغاشية",
      id: "Al Ghashiyah",
      ru: "Аль Гашия",
      cn: "席卷",
      de: "Die überwältigende",
      pt: "A Cobertura",
      th: "อัลกาชิة",
      bn: "সূرا الغاشية",
      fa: "غاشية",
      tr: "Ghashiye",
      bs: "Ghashiyah",
      ug: "الغاشية",
      tg: "Ғошия",
      ml: "അല് الغَاشِيَة",
      tl: "Al Ghashiyah",
      ha: "Al Ghashiyah",
      sw: "Al Ghashiyah",
    },
  },
  {
    number: 89,
    name: {
      ar: "الفجر",
      eng: "Al Fajr",
      fr: "Al Fajr",
      es: "Al Fajr",
      ur: "الفجر",
      id: "Al Fajr",
      ru: "Аль Фаджр",
      cn: "黎明",
      de: "Die Morgendämmerung",
      pt: "A Aurora",
      th: "อัลฟجر",
      bn: "সূরা الفجر",
      fa: "فجر",
      tr: "Fecr",
      bs: "Fecir",
      ug: "فجر",
      tg: "Фаджр",
      ml: "അل الفَجْر",
      tl: "Al Fajr",
      ha: "Al Fajr",
      sw: "Al Fajr",
    },
  },
  {
    number: 90,
    name: {
      ar: "البلد",
      eng: "Al Balad",
      fr: "Al Balad",
      es: "Al Balad",
      ur: "البلد",
      id: "Al Balad",
      ru: "Аль Балад",
      cn: "城",
      de: "Die Stadt",
      pt: "A Cidade",
      th: "อัลบะลัด",
      bn: "সূরা البلد",
      fa: "بلد",
      tr: "Belad",
      bs: "Balad",
      ug: "بلد",
      tg: "Шаҳар",
      ml: "അل الْبَلَد",
      tl: "Al Balad",
      ha: "Al Balad",
      sw: "Al Balad",
    },
  },
  {
    number: 91,
    name: {
      ar: "الشمس",
      eng: "Ash Shams",
      fr: "Ash Shams",
      es: "Ash Shams",
      ur: "الشمس",
      id: "Ash Shams",
      ru: "Аш Шамс",
      cn: "太阳",
      de: "Die Sonne",
      pt: "O Sol",
      th: "อัลชัมس",
      bn: "সূরা الشمس",
      fa: "شمس",
      tr: "Şems",
      bs: "Şems",
      ug: "شمس",
      tg: "Шамс",
      ml: "അل الشَّمْس",
      tl: "Ash Shams",
      ha: "Ash Shams",
      sw: "Ash Shams",
    },
  },
  {
    number: 92,
    name: {
      ar: "الليل",
      eng: "Al Lail",
      fr: "Al Lail",
      es: "Al Lail",
      ur: "الليل",
      id: "Al Lail",
      ru: "Аль Лейл",
      cn: "夜",
      de: "Die Nacht",
      pt: "A Noite",
      th: "อัลลัยل",
      bn: "সূরা الليل",
      fa: "لیل",
      tr: "Leyl",
      bs: "Lejl",
      ug: "ليل",
      tg: "Шаб",
      ml: "അل اللَّيْل",
      tl: "Al Lail",
      ha: "Al Lail",
      sw: "Al Lail",
    },
  },
  {
    number: 93,
    name: {
      ar: "الضحى",
      eng: "Ad Duha",
      fr: "Ad Duha",
      es: "Ad Duha",
      ur: "الضحى",
      id: "Ad Duha",
      ru: "Аль Духа",
      cn: "晨光",
      de: "Die Morgenstunden",
      pt: "A Manhã",
      th: "อัดดูحى",
      bn: "সূরা الضحى",
      fa: "ضحى",
      tr: "Duha",
      bs: "Duhā",
      ug: "ضحى",
      tg: "Дуҳа",
      ml: "അل الضُّحَى",
      tl: "Ad Duha",
      ha: "Ad Duha",
      sw: "Ad Duha",
    },
  },
  {
    number: 94,
    name: {
      ar: "الشرح",
      eng: "Al Inshirah",
      fr: "Al Inshirah",
      es: "Al Inshirah",
      ur: "الشرح",
      id: "Al Inshirah",
      ru: "Аль Инширах",
      cn: "舒畅",
      de: "Die Öffnung",
      pt: "A Expansão",
      th: "อัลชَّرْح",
      bn: "সূরা الشرح",
      fa: "شرح",
      tr: "İnşirah",
      bs: "İnşirah",
      ug: "الشرح",
      tg: "Шарҳ",
      ml: "അل الشَّرْح",
      tl: "Al Inshirah",
      ha: "Al Inshirah",
      sw: "Al Inshirah",
    },
  },
  {
    number: 95,
    name: {
      ar: "التين",
      eng: "At Tin",
      fr: "At Tin",
      es: "At Tin",
      ur: "التين",
      id: "At Tin",
      ru: "Ат Тин",
      cn: "无花果",
      de: "Der Feigenbaum",
      pt: "A Figueira",
      th: "อัลติน",
      bn: "সূরা التين",
      fa: "تین",
      tr: "Tin",
      bs: "Tin",
      ug: "التين",
      tg: "Тин",
      ml: "അل التِّين",
      tl: "At Tin",
      ha: "At Tin",
      sw: "At Tin",
    },
  },
  {
    number: 96,
    name: {
      ar: "العلق",
      eng: "Al Alaq",
      fr: "Al Alaq",
      es: "Al Alaq",
      ur: "العلق",
      id: "Al Alaq",
      ru: "Аль Алак",
      cn: "凝聚",
      de: "Der Klumpen",
      pt: "O Coágulo",
      th: "อัลอَلَق",
      bn: "সূরা العلق",
      fa: "علق",
      tr: "Alaq",
      bs: "Alaq",
      ug: "علق",
      tg: "Алак",
      ml: "അل الْعَلَق",
      tl: "Al Alaq",
      ha: "Al Alaq",
      sw: "Al Alaq",
    },
  },
  {
    number: 97,
    name: {
      ar: "القدر",
      eng: "Al Qadr",
      fr: "Al Qadr",
      es: "Al Qadr",
      ur: "القدر",
      id: "Al Qadr",
      ru: "Аль Кадар",
      cn: "命运",
      de: "Die Bestimmung",
      pt: "A Determinação",
      th: "อัลกะดร",
      bn: "সূরা القدر",
      fa: "قدر",
      tr: "Kadir",
      bs: "Kadir",
      ug: "قدر",
      tg: "Қадр",
      ml: "അل الْقَدْر",
      tl: "Al Qadr",
      ha: "Al Qadr",
      sw: "Al Qadr",
    },
  },
  {
    number: 98,
    name: {
      ar: "البينة",
      eng: "Al Bayyina",
      fr: "Al Bayyina",
      es: "Al Bayyina",
      ur: "البينة",
      id: "Al Bayyina",
      ru: "Аль Баййина",
      cn: "明证",
      de: "Der klare Beweis",
      pt: "A Prova",
      th: "อัลบัยّنة",
      bn: "সূরা البينة",
      fa: "بیّنه",
      tr: "Beyyine",
      bs: "Beyyinah",
      ug: "البينة",
      tg: "Баййина",
      ml: "അل الْبَيِّنَة",
      tl: "Al Bayyina",
      ha: "Al Bayyina",
      sw: "Al Bayyina",
    },
  },
  {
    number: 99,
    name: {
      ar: "الزلزلة",
      eng: "Az Zalzalah",
      fr: "Az Zalzalah",
      es: "Az Zalzalah",
      ur: "الزلزلة",
      id: "Az Zalzalah",
      ru: "Аз Зальзала",
      cn: "震动",
      de: "Das Erdbeben",
      pt: "O Tremor",
      th: "อัลซัลซะลَه",
      bn: "সূরা الزلزلة",
      fa: "زلزله",
      tr: "Zalzala",
      bs: "Zalzala",
      ug: "زلزلة",
      tg: "Залзала",
      ml: "അل الْزَلْزَلَة",
      tl: "Az Zalzalah",
      ha: "Az Zalzalah",
      sw: "Az Zalzalah",
    },
  },
  {
    number: 100,
    name: {
      ar: "العاديات",
      eng: "Al Adiyat",
      fr: "Al Adiyat",
      es: "Al Adiyat",
      ur: "العاديات",
      id: "Al Adiyat",
      ru: "Аль Адият",
      cn: "战马",
      de: "Die Schnellsten",
      pt: "Os Garranos",
      th: "อัลอาดีَات",
      bn: "সূرا العاديات",
      fa: "عادیات",
      tr: "Adiyat",
      bs: "Adiyat",
      ug: "عاديات",
      tg: "Адиёт",
      ml: "അل العَادِيَات",
      tl: "Al Adiyat",
      ha: "Al Adiyat",
      sw: "Al Adiyat",
    },
  },
  {
    number: 101,
    name: {
      ar: "القارعة",
      eng: "Al Qari'a",
      fr: "Al Qari'a",
      es: "Al Qari'a",
      ur: "القارعة",
      id: "Al Qari'a",
      ru: "Аль Каръиа",
      cn: "灾难",
      de: "Die Katastrophe",
      pt: "A Calamidade",
      th: "อัลคอรีอะ",
      bn: "সূرا القارعة",
      fa: "قارعه",
      tr: "Kari'a",
      bs: "Kari'a",
      ug: "القارعة",
      tg: "Қаръиа",
      ml: "അل القَارِعَة",
      tl: "Al Qari'a",
      ha: "Al Qari'a",
      sw: "Al Qari'a",
    },
  },
  {
    number: 102,
    name: {
      ar: "التكاثر",
      eng: "At Takathur",
      fr: "At Takathur",
      es: "At Takathur",
      ur: "التكاثر",
      id: "At Takathur",
      ru: "Ат Такасур",
      cn: "追求财富",
      de: "Die Mehrung",
      pt: "A Multiplicação",
      th: "อัลตักษุร",
      bn: "সূرا التكاثر",
      fa: "تکاثر",
      tr: "Tekasür",
      bs: "Tekasür",
      ug: "التكاثر",
      tg: "Такосур",
      ml: "അل التَّكَاثُر",
      tl: "At Takathur",
      ha: "At Takathur",
      sw: "At Takathur",
    },
  },
  {
    number: 103,
    name: {
      ar: "العصر",
      eng: "Al Asr",
      fr: "Al Asr",
      es: "Al Asr",
      ur: "العصر",
      id: "Al Asr",
      ru: "Аль Аср",
      cn: "时代",
      de: "Die Zeit",
      pt: "O Tempo",
      th: "อัลอัศْر",
      bn: "সূرا العصر",
      fa: "عصر",
      tr: "Asr",
      bs: "Asr",
      ug: "العصر",
      tg: "Аср",
      ml: "അل الْعَصْر",
      tl: "Al Asr",
      ha: "Al Asr",
      sw: "Al Asr",
    },
  },
  {
    number: 104,
    name: {
      ar: "الهُمَزَة",
      eng: "Al Humazah",
      fr: "Al Humazah",
      es: "Al Humazah",
      ur: "الهُمَزَة",
      id: "Al Humazah",
      ru: "Аль Хумаза",
      cn: "诽谤者",
      de: "Der Verleumder",
      pt: "O Caluniador",
      th: "อัลฮุมะซะة",
      bn: "সূرا الهمزة",
      fa: "همزه",
      tr: "Humazah",
      bs: "Humazah",
      ug: "الهُمَزَة",
      tg: "Ҳумаза",
      ml: "അل الْهُمَزَة",
      tl: "Al Humazah",
      ha: "Al Humazah",
      sw: "Al Humazah",
    },
  },
  {
    number: 105,
    name: {
      ar: "الفيل",
      eng: "Al Fil",
      fr: "Al Fil",
      es: "Al Fil",
      ur: "الفيل",
      id: "Al Fil",
      ru: "Аль Филь",
      cn: "大象",
      de: "Der Elefant",
      pt: "O Elefante",
      th: "อัลฟีล",
      bn: "সূرا الفيل",
      fa: "فیل",
      tr: "Fil",
      bs: "Fil",
      ug: "الفيل",
      tg: "Фил",
      ml: "അل الفِيل",
      tl: "Al Fil",
      ha: "Al Fil",
      sw: "Al Fil",
    },
  },
  {
    number: 106,
    name: {
      ar: "قريش",
      eng: "Quraish",
      fr: "Quraish",
      es: "Quraish",
      ur: "قريش",
      id: "Quraish",
      ru: "Курайш",
      cn: "古来什",
      de: "Die Quraisch",
      pt: "Os Corais",
      th: "อัลกุเรช",
      bn: "সূرا قريش",
      fa: "قریش",
      tr: "Kureyş",
      bs: "Kureyş",
      ug: "قريش",
      tg: "Қурайш",
      ml: "അല قُرَيْش",
      tl: "Quraish",
      ha: "Quraish",
      sw: "Quraish",
    },
  },
  {
    number: 107,
    name: {
      ar: "الماعون",
      eng: "Al Ma'un",
      fr: "Al Ma'un",
      es: "Al Ma'un",
      ur: "الماعون",
      id: "Al Ma'un",
      ru: "Аль Маун",
      cn: "施舍",
      de: "Die Almosen",
      pt: "A Caridade",
      th: "อัลมาชูน",
      bn: "সূرا المعون",
      fa: "ماعون",
      tr: "Ma'un",
      bs: "Ma'un",
      ug: "الماعون",
      tg: "Маун",
      ml: "അل المَاعُون",
      tl: "Al Ma'un",
      ha: "Al Ma'un",
      sw: "Al Ma'un",
    },
  },
  {
    number: 108,
    name: {
      ar: "الكوثر",
      eng: "Al Kawthar",
      fr: "Al Kawthar",
      es: "Al Kawthar",
      ur: "الكوثر",
      id: "Al Kawthar",
      ru: "Аль Каусар",
      cn: "丰盛",
      de: "Die Fülle",
      pt: "A Abundância",
      th: "อัลคอثر",
      bn: "সূرا الكوثر",
      fa: "کوثر",
      tr: "Kavsar",
      bs: "Kavsar",
      ug: "الكوثر",
      tg: "Каусар",
      ml: "അل الكَوْثَر",
      tl: "Al Kawthar",
      ha: "Al Kawthar",
      sw: "Al Kawthar",
    },
  },
  {
    number: 109,
    name: {
      ar: "الكافرون",
      eng: "Al Kafirun",
      fr: "Al Kafirun",
      es: "Al Kafirun",
      ur: "الكافرون",
      id: "Al Kafirun",
      ru: "Аль Кафирун",
      cn: "不信者",
      de: "Die Ungläubigen",
      pt: "Os Incrédulos",
      th: "อัลคาฟِرُون",
      bn: "সূرا الكافرون",
      fa: "کافرون",
      tr: "Kafirun",
      bs: "Kafirun",
      ug: "الكافرون",
      tg: "Кофирун",
      ml: "അل الكَافِرُون",
      tl: "Al Kafirun",
      ha: "Al Kafirun",
      sw: "Al Kafirun",
    },
  },
  {
    number: 110,
    name: {
      ar: "النصر",
      eng: "An Nasr",
      fr: "An Nasr",
      es: "An Nasr",
      ur: "النصر",
      id: "An Nasr",
      ru: "Ан Наср",
      cn: "胜利",
      de: "Der Sieg",
      pt: "A Vitória",
      th: "อัลนصر",
      bn: "সূرا النصر",
      fa: "نصر",
      tr: "Nasr",
      bs: "Nasr",
      ug: "النصر",
      tg: "Наср",
      ml: "അل النَّصْر",
      tl: "An Nasr",
      ha: "An Nasr",
      sw: "An Nasr",
    },
  },
  {
    number: 111,
    name: {
      ar: "المسد",
      eng: "Al Masad",
      fr: "Al Masad",
      es: "Al Masad",
      ur: "المسد",
      id: "Al Masad",
      ru: "Аль Масад",
      cn: "绳索",
      de: "Die Faser",
      pt: "A Fibras",
      th: "อัลมัสด",
      bn: "সূرا المسد",
      fa: "مسد",
      tr: "Mesed",
      bs: "Mesed",
      ug: "المسد",
      tg: "Масад",
      ml: "അل المَسَد",
      tl: "Al Masad",
      ha: "Al Masad",
      sw: "Al Masad",
    },
  },
  {
    number: 112,
    name: {
      ar: "الإخلاص",
      eng: "Al Ikhlas",
      fr: "Al Ikhlas",
      es: "Al Ikhlas",
      ur: "الإخلاص",
      id: "Al Ikhlas",
      ru: "Аль Ихлас",
      cn: "真诚",
      de: "Die Aufrichtigkeit",
      pt: "A Sinceridade",
      th: "อัลอิคลาส",
      bn: "সূرا الإخلاص",
      fa: "اخلاص",
      tr: "İhlâs",
      bs: "İhlâs",
      ug: "الإخلاص",
      tg: "Ихлас",
      ml: "അل الإخْلَاص",
      tl: "Al Ikhlas",
      ha: "Al Ikhlas",
      sw: "Al Ikhlas",
    },
  },
  {
    number: 113,
    name: {
      ar: "الفلق",
      eng: "Al Falaq",
      fr: "Al Falaq",
      es: "Al Falaq",
      ur: "الفلق",
      id: "Al Falaq",
      ru: "Аль Фаляк",
      cn: "破晓",
      de: "Die Morgenröte",
      pt: "A Alvorada",
      th: "อัลฟَلَق",
      bn: "সূرا الفلق",
      fa: "فلق",
      tr: "Felak",
      bs: "Felak",
      ug: "الفلق",
      tg: "Фалақ",
      ml: "അل الفَلَق",
      tl: "Al Falaq",
      ha: "Al Falaq",
      sw: "Al Falaq",
    },
  },
  {
    number: 114,
    name: {
      ar: "الناس",
      eng: "An Nas",
      fr: "An Nas",
      es: "An Nas",
      ur: "الناس",
      id: "An Nas",
      ru: "Ан Нас",
      cn: "人类",
      de: "Die Menschen",
      pt: "A Humanidade",
      th: "อัลนาส",
      bn: "সূرا الناس",
      fa: "ناس",
      tr: "Nas",
      bs: "Nas",
      ug: "الناس",
      tg: "Нас",
      ml: "അل النَّاس",
      tl: "An Nas",
      ha: "An Nas",
      sw: "An Nas",
    },
  },
];
